export const APP_VERSION = '2.0.3';
export const APP_BUILD_DATE = '2026-01-16';
export const VERSION_HISTORY = [
  { version: '2.0.3', date: '2026-01-16', changes: 'Alterado nome do app para "Editor IO" no power.config.json e index.html.' },
  { version: '2.0.2', date: '2026-01-16', changes: 'Adicionado label com número de versão do app no canto superior direito de todas as telas.' },
  { version: '2.0.1', date: '2026-01-16', changes: 'Removido ícone BuildingRegular dos cards de fabricantes na tela principal.' },
  { version: '2.0.0', date: '2026-01-16', changes: 'Redesign completo da UI: implementado Fluent UI v9 com tema PowerApps Model-Driven, novos componentes (Cards, SearchBox, Dropdown, Dialog, Accordion), shell com header estilo PowerApps, melhor hierarquia visual e experiência do usuário.' },
  { version: '1.0.12', date: '2026-01-16', changes: 'Implementado auto-save: alteracoes em conexoes, dimensoes e categoria sao salvas automaticamente no Dataverse.' },
  { version: '1.0.11', date: '2026-01-16', changes: 'Traduzidos labels Inputs/Outputs para Entradas/Saidas.' },
  { version: '1.0.10', date: '2026-01-16', changes: 'Indicadas as secoes de conexoes por direcao.' },
  { version: '1.0.9', date: '2026-01-16', changes: 'Ajustado tema para light como padrao no app.' },
  { version: '1.0.8', date: '2026-01-16', changes: 'Separadas conexoes em Inputs, Outputs e Bidirecionais/Bus.' },
  { version: '1.0.7', date: '2026-01-16', changes: 'Busca de produtos com debounce e input persistente para evitar perda de foco.' },
  { version: '1.0.6', date: '2026-01-16', changes: 'Busca de fabricantes com debounce e input persistente para evitar perda de foco.' },
  { version: '1.0.5', date: '2026-01-16', changes: 'Integrada tabela de fabricantes e buscas delegaveis para fabricantes e produtos.' },
  { version: '1.0.4', date: '2026-01-16', changes: 'Adicionado filtro statecode eq 0 na query de fabricantes para retornar apenas produtos ativos.' },
  { version: '1.0.3', date: '2026-01-16', changes: 'Adicionada busca por fabricante na tela inicial.' },
  { version: '1.0.2', date: '2026-01-16', changes: 'Restaurada configuracao do Vite para porta 3000 exigida pelo Power Apps.' },
  { version: '1.0.1', date: '2026-01-16', changes: 'Suprimidos warnings do StrictMode e tratadas promessas ao salvar o template.' },
  { version: '1.0.0', date: '2026-01-16', changes: 'Implementada interface completa do editor de IOs: navegacao Fabricantes > Produtos > Editor, conexoes editaveis com tipos/direcoes, salvamento no Dataverse.' },
  { version: '0.0.6', date: '2026-01-16', changes: 'Adicionadas instruções obrigatórias no copilot-instructions.md para gerar metadados PAC ao importar tabelas do Dataverse.' },
  { version: '0.0.5', date: '2026-01-16', changes: 'Gerados metadados das tabelas new_deviceio e new_deviceioconnection e atualizado DATAVERSE_METADATA.md.' },
  { version: '0.0.4', date: '2026-01-16', changes: 'Documentado passo a passo completo para importar tabelas do Dataverse em copilot-instructions.md.' },
  { version: '0.0.3', date: '2026-01-16', changes: 'Mapeado o data source cr22f_modelosdeprodutofromsharepointlists em power.config.json.' },
  { version: '0.0.2', date: '2026-01-16', changes: 'Importada a tabela cr22f_modelosdeprodutofromsharepointlist do Dataverse; gerado serviço e metadados iniciais.' },
  { version: '0.0.1', date: '2026-01-16', changes: 'Atualizado o nome do projeto para editor-io-dispositivos.' },
];
