#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Estoque From SharepointList
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr22f_estoquefromsharepointlist_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Estoque From SharepointList
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr22f_estoquefromsharepointlist_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cr22f_estoquefromsharepointlist")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class cr22f_EstoqueFromSharepointList : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public cr22f_EstoqueFromSharepointList() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "cr22f_estoquefromsharepointlist";
	
	public const string EntityLogicalCollectionName = "cr22f_estoquefromsharepointlists";
	
	public const string EntitySetName = "cr22f_estoquefromsharepointlists";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_color")]
	public string cr22f_Color
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_color");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Color");
			this.SetAttributeValue("cr22f_color", value);
			this.OnPropertyChanged("cr22f_Color");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_conditionnotes")]
	public string cr22f_ConditionNotes
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_conditionnotes");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ConditionNotes");
			this.SetAttributeValue("cr22f_conditionnotes", value);
			this.OnPropertyChanged("cr22f_ConditionNotes");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_contatofaturamentoid")]
	public string cr22f_ContatoFaturamentoId
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_contatofaturamentoid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ContatoFaturamentoId");
			this.SetAttributeValue("cr22f_contatofaturamentoid", value);
			this.OnPropertyChanged("cr22f_ContatoFaturamentoId");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_estoquefromsharepointlistid")]
	public System.Nullable<System.Guid> cr22f_EstoqueFromSharepointListId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("cr22f_estoquefromsharepointlistid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_EstoqueFromSharepointListId");
			this.SetAttributeValue("cr22f_estoquefromsharepointlistid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("cr22f_EstoqueFromSharepointListId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_estoquefromsharepointlistid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.cr22f_EstoqueFromSharepointListId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_fornecedorid")]
	public System.Nullable<int> cr22f_FornecedorId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_fornecedorid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_FornecedorId");
			this.SetAttributeValue("cr22f_fornecedorid", value);
			this.OnPropertyChanged("cr22f_FornecedorId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_id")]
	public System.Nullable<int> cr22f_ID
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_id");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ID");
			this.SetAttributeValue("cr22f_id", value);
			this.OnPropertyChanged("cr22f_ID");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_localizao")]
	public string cr22f_Localizao
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_localizao");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Localizao");
			this.SetAttributeValue("cr22f_localizao", value);
			this.OnPropertyChanged("cr22f_Localizao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_modelodoprodutoid")]
	public System.Nullable<int> cr22f_ModelodoprodutoId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_modelodoprodutoid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ModelodoprodutoId");
			this.SetAttributeValue("cr22f_modelodoprodutoid", value);
			this.OnPropertyChanged("cr22f_ModelodoprodutoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_multinsert")]
	public System.Nullable<int> cr22f_MultInsert
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_multinsert");
		}
		set
		{
			this.OnPropertyChanging("cr22f_MultInsert");
			this.SetAttributeValue("cr22f_multinsert", value);
			this.OnPropertyChanged("cr22f_MultInsert");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_nf")]
	public System.Nullable<int> cr22f_NF
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_nf");
		}
		set
		{
			this.OnPropertyChanging("cr22f_NF");
			this.SetAttributeValue("cr22f_nf", value);
			this.OnPropertyChanged("cr22f_NF");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_numberofbackups")]
	public System.Nullable<int> cr22f_NumberOfBackups
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_numberofbackups");
		}
		set
		{
			this.OnPropertyChanging("cr22f_NumberOfBackups");
			this.SetAttributeValue("cr22f_numberofbackups", value);
			this.OnPropertyChanged("cr22f_NumberOfBackups");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_obraid")]
	public System.Nullable<int> cr22f_ObraId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_obraid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ObraId");
			this.SetAttributeValue("cr22f_obraid", value);
			this.OnPropertyChanged("cr22f_ObraId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_ordernumber")]
	public string cr22f_OrderNumber
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_ordernumber");
		}
		set
		{
			this.OnPropertyChanging("cr22f_OrderNumber");
			this.SetAttributeValue("cr22f_ordernumber", value);
			this.OnPropertyChanged("cr22f_OrderNumber");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_purchaseprice")]
	public Microsoft.Xrm.Sdk.Money cr22f_PurchasePrice
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("cr22f_purchaseprice");
		}
		set
		{
			this.OnPropertyChanging("cr22f_PurchasePrice");
			this.SetAttributeValue("cr22f_purchaseprice", value);
			this.OnPropertyChanged("cr22f_PurchasePrice");
		}
	}
	
	/// <summary>
	/// Value of the PurchasePrice in base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_purchaseprice_base")]
	public Microsoft.Xrm.Sdk.Money cr22f_purchaseprice_Base
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("cr22f_purchaseprice_base");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_querycontatofaturamentofornecedo")]
	public string cr22f_QueryContatoFaturamentoFornecedo
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_querycontatofaturamentofornecedo");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryContatoFaturamentoFornecedo");
			this.SetAttributeValue("cr22f_querycontatofaturamentofornecedo", value);
			this.OnPropertyChanged("cr22f_QueryContatoFaturamentoFornecedo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_queryfabricante")]
	public string cr22f_QueryFabricante
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_queryfabricante");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryFabricante");
			this.SetAttributeValue("cr22f_queryfabricante", value);
			this.OnPropertyChanged("cr22f_QueryFabricante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_queryfornecedor")]
	public string cr22f_QueryFornecedor
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_queryfornecedor");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryFornecedor");
			this.SetAttributeValue("cr22f_queryfornecedor", value);
			this.OnPropertyChanged("cr22f_QueryFornecedor");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_querymodeloproduto")]
	public string cr22f_QueryModeloProduto
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_querymodeloproduto");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryModeloProduto");
			this.SetAttributeValue("cr22f_querymodeloproduto", value);
			this.OnPropertyChanged("cr22f_QueryModeloProduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_queryobra")]
	public string cr22f_QueryObra
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_queryobra");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryObra");
			this.SetAttributeValue("cr22f_queryobra", value);
			this.OnPropertyChanged("cr22f_QueryObra");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_querystatus")]
	public string cr22f_QueryStatus
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_querystatus");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryStatus");
			this.SetAttributeValue("cr22f_querystatus", value);
			this.OnPropertyChanged("cr22f_QueryStatus");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_querytag")]
	public System.Nullable<int> cr22f_QueryTag
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_querytag");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryTag");
			this.SetAttributeValue("cr22f_querytag", value);
			this.OnPropertyChanged("cr22f_QueryTag");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_querytipoproduto")]
	public string cr22f_QueryTipoProduto
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_querytipoproduto");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryTipoProduto");
			this.SetAttributeValue("cr22f_querytipoproduto", value);
			this.OnPropertyChanged("cr22f_QueryTipoProduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_serialnumber")]
	public string cr22f_SerialNumber
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_serialnumber");
		}
		set
		{
			this.OnPropertyChanging("cr22f_SerialNumber");
			this.SetAttributeValue("cr22f_serialnumber", value);
			this.OnPropertyChanged("cr22f_SerialNumber");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_status")]
	public string cr22f_Status
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_status");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Status");
			this.SetAttributeValue("cr22f_status", value);
			this.OnPropertyChanged("cr22f_Status");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_tagconfirmada")]
	public System.Nullable<int> cr22f_TagConfirmada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("cr22f_tagconfirmada");
		}
		set
		{
			this.OnPropertyChanging("cr22f_TagConfirmada");
			this.SetAttributeValue("cr22f_tagconfirmada", value);
			this.OnPropertyChanged("cr22f_TagConfirmada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_tagimage")]
	public string cr22f_TagImage
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_tagimage");
		}
		set
		{
			this.OnPropertyChanging("cr22f_TagImage");
			this.SetAttributeValue("cr22f_tagimage", value);
			this.OnPropertyChanged("cr22f_TagImage");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_title")]
	public string cr22f_Title
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_title");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Title");
			this.SetAttributeValue("cr22f_title", value);
			this.OnPropertyChanged("cr22f_Title");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Exchange rate for the currency associated with the entity with respect to the base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_centrodedistribuicao")]
	public virtual new_centrodedistribuicao? new_CentrodeDistribuicao
	{
		get
		{
			return ((new_centrodedistribuicao?)(EntityOptionSetEnum.GetEnum(this, "new_centrodedistribuicao")));
		}
		set
		{
			this.OnPropertyChanging("new_CentrodeDistribuicao");
			this.SetAttributeValue("new_centrodedistribuicao", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_CentrodeDistribuicao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_centrodedistribuicaotexto")]
	public string new_CentrodeDistribuicaoTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_centrodedistribuicaotexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_classecriticidade")]
	public virtual new_classedeproduto? new_ClasseCriticidade
	{
		get
		{
			return ((new_classedeproduto?)(EntityOptionSetEnum.GetEnum(this, "new_classecriticidade")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clientefx")]
	public string new_ClienteFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_clientefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_confirmacaodeetiqueta")]
	public string new_ConfirmacaodeEtiqueta
	{
		get
		{
			return this.GetAttributeValue<string>("new_confirmacaodeetiqueta");
		}
		set
		{
			this.OnPropertyChanging("new_ConfirmacaodeEtiqueta");
			this.SetAttributeValue("new_confirmacaodeetiqueta", value);
			this.OnPropertyChanged("new_ConfirmacaodeEtiqueta");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_confirmacaodetag")]
	public string new_ConfirmacaodeTag
	{
		get
		{
			return this.GetAttributeValue<string>("new_confirmacaodetag");
		}
		set
		{
			this.OnPropertyChanging("new_ConfirmacaodeTag");
			this.SetAttributeValue("new_confirmacaodetag", value);
			this.OnPropertyChanged("new_ConfirmacaodeTag");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contemrma")]
	public System.Nullable<bool> new_ContemRMA
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_contemrma");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contemrmaespelho")]
	public System.Nullable<bool> new_ContemRMAEspelho
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_contemrmaespelho");
		}
		set
		{
			this.OnPropertyChanging("new_ContemRMAEspelho");
			this.SetAttributeValue("new_contemrmaespelho", value);
			this.OnPropertyChanged("new_ContemRMAEspelho");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaleitura")]
	public System.Nullable<System.DateTime> new_DatadaUltimaLeitura
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaleitura");
		}
		set
		{
			this.OnPropertyChanging("new_DatadaUltimaLeitura");
			this.SetAttributeValue("new_datadaultimaleitura", value);
			this.OnPropertyChanged("new_DatadaUltimaLeitura");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_deposito")]
	public virtual new_deposito? new_Deposito
	{
		get
		{
			return ((new_deposito?)(EntityOptionSetEnum.GetEnum(this, "new_deposito")));
		}
		set
		{
			this.OnPropertyChanging("new_Deposito");
			this.SetAttributeValue("new_deposito", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_Deposito");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_depositotexto")]
	public string new_DepositoTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_depositotexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_endereco")]
	public string new_Endereco
	{
		get
		{
			return this.GetAttributeValue<string>("new_endereco");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_estante")]
	public virtual new_estantedeposito? new_Estante
	{
		get
		{
			return ((new_estantedeposito?)(EntityOptionSetEnum.GetEnum(this, "new_estante")));
		}
		set
		{
			this.OnPropertyChanging("new_Estante");
			this.SetAttributeValue("new_estante", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_Estante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_estantetexto")]
	public string new_EstanteTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_estantetexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_etiquetaemtextocalculated")]
	public string new_EtiquetaEmTextoCalculated
	{
		get
		{
			return this.GetAttributeValue<string>("new_etiquetaemtextocalculated");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fabricantecalculado")]
	public string new_FabricanteCalculado
	{
		get
		{
			return this.GetAttributeValue<string>("new_fabricantecalculado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fabricantefx")]
	public string new_FabricanteFX
	{
		get
		{
			return this.GetAttributeValue<string>("new_fabricantefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fotodoproduto")]
	public byte[] new_FotodoProduto
	{
		get
		{
			return this.GetAttributeValue<byte[]>("new_fotodoproduto");
		}
		set
		{
			this.OnPropertyChanging("new_FotodoProduto");
			this.SetAttributeValue("new_fotodoproduto", value);
			this.OnPropertyChanged("new_FotodoProduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fotodoproduto_timestamp")]
	public System.Nullable<long> new_FotodoProduto_Timestamp
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("new_fotodoproduto_timestamp");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fotodoproduto_url")]
	public string new_FotodoProduto_URL
	{
		get
		{
			return this.GetAttributeValue<string>("new_fotodoproduto_url");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fotodoprodutoid")]
	public System.Nullable<System.Guid> new_FotodoProdutoId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_fotodoprodutoid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fotodoprodutourl")]
	public string new_FotodoProdutoURL
	{
		get
		{
			return this.GetAttributeValue<string>("new_fotodoprodutourl");
		}
		set
		{
			this.OnPropertyChanging("new_FotodoProdutoURL");
			this.SetAttributeValue("new_fotodoprodutourl", value);
			this.OnPropertyChanged("new_FotodoProdutoURL");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grupodeorigem")]
	public Microsoft.Xrm.Sdk.EntityReference new_GrupodeOrigem
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_grupodeorigem");
		}
		set
		{
			this.OnPropertyChanging("new_GrupodeOrigem");
			this.SetAttributeValue("new_grupodeorigem", value);
			this.OnPropertyChanged("new_GrupodeOrigem");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_idtext")]
	public string new_IdText
	{
		get
		{
			return this.GetAttributeValue<string>("new_idtext");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_imagemetiquetapng")]
	public byte[] new_ImagemEtiquetaPNG
	{
		get
		{
			return this.GetAttributeValue<byte[]>("new_imagemetiquetapng");
		}
		set
		{
			this.OnPropertyChanging("new_ImagemEtiquetaPNG");
			this.SetAttributeValue("new_imagemetiquetapng", value);
			this.OnPropertyChanged("new_ImagemEtiquetaPNG");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_imagemetiquetapng_timestamp")]
	public System.Nullable<long> new_ImagemEtiquetaPNG_Timestamp
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("new_imagemetiquetapng_timestamp");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_imagemetiquetapng_url")]
	public string new_ImagemEtiquetaPNG_URL
	{
		get
		{
			return this.GetAttributeValue<string>("new_imagemetiquetapng_url");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_imagemetiquetapngid")]
	public System.Nullable<System.Guid> new_ImagemEtiquetaPNGId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_imagemetiquetapngid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_insercao")]
	public Microsoft.Xrm.Sdk.EntityReference new_Insercao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_insercao");
		}
		set
		{
			this.OnPropertyChanging("new_Insercao");
			this.SetAttributeValue("new_insercao", value);
			this.OnPropertyChanged("new_Insercao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_mercadoriaanteriordorma")]
	public Microsoft.Xrm.Sdk.EntityReference new_MercadoriaAnteriordoRMA
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_mercadoriaanteriordorma");
		}
		set
		{
			this.OnPropertyChanging("new_MercadoriaAnteriordoRMA");
			this.SetAttributeValue("new_mercadoriaanteriordorma", value);
			this.OnPropertyChanged("new_MercadoriaAnteriordoRMA");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_mercadoriatravada")]
	public System.Nullable<bool> new_MercadoriaTravada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_mercadoriatravada");
		}
		set
		{
			this.OnPropertyChanging("new_MercadoriaTravada");
			this.SetAttributeValue("new_mercadoriatravada", value);
			this.OnPropertyChanged("new_MercadoriaTravada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_modelodeproduto")]
	public Microsoft.Xrm.Sdk.EntityReference new_ModelodeProduto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_modelodeproduto");
		}
		set
		{
			this.OnPropertyChanging("new_ModelodeProduto");
			this.SetAttributeValue("new_modelodeproduto", value);
			this.OnPropertyChanged("new_ModelodeProduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodermas")]
	public System.Nullable<int> new_NumerodeRMAs
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodermas");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de RMAs.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodermas_date")]
	public System.Nullable<System.DateTime> new_NumerodeRMAs_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodermas_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de RMAs.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodermas_state")]
	public System.Nullable<int> new_NumerodeRMAs_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodermas_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodermasnovoproduto")]
	public System.Nullable<int> new_NumerodeRMAsNovoProduto
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodermasnovoproduto");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de RMAs (Novo Produto).
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodermasnovoproduto_date")]
	public System.Nullable<System.DateTime> new_NumerodeRMAsNovoProduto_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodermasnovoproduto_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de RMAs (Novo Produto).
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodermasnovoproduto_state")]
	public System.Nullable<int> new_NumerodeRMAsNovoProduto_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodermasnovoproduto_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodorecibo")]
	public string new_NumerodoRecibo
	{
		get
		{
			return this.GetAttributeValue<string>("new_numerodorecibo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_ordemdeservico");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServico");
			this.SetAttributeValue("new_ordemdeservico", value);
			this.OnPropertyChanged("new_OrdemdeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_osfx")]
	public string new_OSFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_osfx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prateleira")]
	public virtual new_prateleiradeposito? new_Prateleira
	{
		get
		{
			return ((new_prateleiradeposito?)(EntityOptionSetEnum.GetEnum(this, "new_prateleira")));
		}
		set
		{
			this.OnPropertyChanging("new_Prateleira");
			this.SetAttributeValue("new_prateleira", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_Prateleira");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prateleiratexto")]
	public string new_PrateleiraTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_prateleiratexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_precodecompraatualizado")]
	public Microsoft.Xrm.Sdk.Money new_PrecodeCompraAtualizado
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_precodecompraatualizado");
		}
		set
		{
			this.OnPropertyChanging("new_PrecodeCompraAtualizado");
			this.SetAttributeValue("new_precodecompraatualizado", value);
			this.OnPropertyChanged("new_PrecodeCompraAtualizado");
		}
	}
	
	/// <summary>
	/// Value of the Preço de Compra Atualizado in base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_precodecompraatualizado_base")]
	public Microsoft.Xrm.Sdk.Money new_precodecompraatualizado_Base
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_precodecompraatualizado_base");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_produtoservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_ProdutoServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_produtoservico");
		}
		set
		{
			this.OnPropertyChanging("new_ProdutoServico");
			this.SetAttributeValue("new_produtoservico", value);
			this.OnPropertyChanged("new_ProdutoServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidade")]
	public System.Nullable<int> new_Quantidade
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidade");
		}
		set
		{
			this.OnPropertyChanging("new_Quantidade");
			this.SetAttributeValue("new_quantidade", value);
			this.OnPropertyChanged("new_Quantidade");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedevolvidos")]
	public System.Nullable<int> new_QuantidadeDevolvidos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidadedevolvidos");
		}
		set
		{
			this.OnPropertyChanging("new_QuantidadeDevolvidos");
			this.SetAttributeValue("new_quantidadedevolvidos", value);
			this.OnPropertyChanged("new_QuantidadeDevolvidos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedisponiveldevolucao")]
	public System.Nullable<decimal> new_QuantidadeDisponivelDevolucao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_quantidadedisponiveldevolucao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_referenciadoproduto")]
	public string new_ReferenciadoProduto
	{
		get
		{
			return this.GetAttributeValue<string>("new_referenciadoproduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_remessa")]
	public Microsoft.Xrm.Sdk.EntityReference new_Remessa
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_remessa");
		}
		set
		{
			this.OnPropertyChanging("new_Remessa");
			this.SetAttributeValue("new_remessa", value);
			this.OnPropertyChanged("new_Remessa");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavenda")]
	public System.Nullable<bool> new_RMAAprovadoParaVenda
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_rmaaprovadoparavenda");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavendanovoproduto")]
	public System.Nullable<int> new_RMAAprovadoParaVendaNovoProduto
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_rmaaprovadoparavendanovoproduto");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field RMA Aprovado Para Venda (Novo Produto).
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavendanovoproduto_date")]
	public System.Nullable<System.DateTime> new_RMAAprovadoParaVendaNovoProduto_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_rmaaprovadoparavendanovoproduto_date");
		}
	}
	
	/// <summary>
	/// State of rollup field RMA Aprovado Para Venda (Novo Produto).
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavendanovoproduto_state")]
	public System.Nullable<int> new_RMAAprovadoParaVendaNovoProduto_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_rmaaprovadoparavendanovoproduto_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavendaprodutoantigo")]
	public System.Nullable<int> new_RMAAprovadoParaVendaProdutoAntigo
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_rmaaprovadoparavendaprodutoantigo");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field RMA Aprovado Para Venda (Produto Antigo).
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavendaprodutoantigo_date")]
	public System.Nullable<System.DateTime> new_RMAAprovadoParaVendaProdutoAntigo_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_rmaaprovadoparavendaprodutoantigo_date");
		}
	}
	
	/// <summary>
	/// State of rollup field RMA Aprovado Para Venda (Produto Antigo).
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaaprovadoparavendaprodutoantigo_state")]
	public System.Nullable<int> new_RMAAprovadoParaVendaProdutoAntigo_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_rmaaprovadoparavendaprodutoantigo_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rua")]
	public virtual new_ruadeposito? new_Rua
	{
		get
		{
			return ((new_ruadeposito?)(EntityOptionSetEnum.GetEnum(this, "new_rua")));
		}
		set
		{
			this.OnPropertyChanging("new_Rua");
			this.SetAttributeValue("new_rua", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_Rua");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ruatexto")]
	public string new_RuaTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_ruatexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_separado")]
	public System.Nullable<bool> new_Separado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_separado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tagconfirmadabool")]
	public System.Nullable<bool> new_TagConfirmadaBool
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_tagconfirmadabool");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ultimacontagem")]
	public System.Nullable<System.DateTime> new_UltimaContagem
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_ultimacontagem");
		}
		set
		{
			this.OnPropertyChanging("new_UltimaContagem");
			this.SetAttributeValue("new_ultimacontagem", value);
			this.OnPropertyChanged("new_UltimaContagem");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Estoque From SharepointList
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual cr22f_estoquefromsharepointlist_statecode? statecode
	{
		get
		{
			return ((cr22f_estoquefromsharepointlist_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Estoque From SharepointList
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual cr22f_estoquefromsharepointlist_statuscode? statuscode
	{
		get
		{
			return ((cr22f_estoquefromsharepointlist_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the currency associated with the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist" +
		"", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<cr22f_EstoqueFromSharepointList> Referencednew_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist
	{
		get
		{
			return this.GetRelatedEntities<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist" +
					"", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencednew_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromshar" +
					"epointlist");
			this.SetRelatedEntities<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist" +
					"", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencednew_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromshar" +
					"epointlist");
		}
	}
	
	/// <summary>
	/// 1:N new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromsharepointlist
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromshar" +
		"epointlist", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<cr22f_EstoqueFromSharepointList> Referencednew_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromsharepointlist
	{
		get
		{
			return this.GetRelatedEntities<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromshar" +
					"epointlist", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencednew_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoq" +
					"uefromsharepointlist");
			this.SetRelatedEntities<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromshar" +
					"epointlist", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencednew_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoq" +
					"uefromsharepointlist");
		}
	}
	
	/// <summary>
	/// N:1 new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grupodeorigem")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist" +
		"", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public cr22f_EstoqueFromSharepointList Referencingnew_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist
	{
		get
		{
			return this.GetRelatedEntity<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist" +
					"", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingnew_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsha" +
					"repointlist");
			this.SetRelatedEntity<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsharepointlist" +
					"", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingnew_cr22f_estoquefromsharepointlist_GrupodeOrigem_cr22f_estoquefromsha" +
					"repointlist");
		}
	}
	
	/// <summary>
	/// N:1 new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromsharepointlist
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_mercadoriaanteriordorma")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromshar" +
		"epointlist", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public cr22f_EstoqueFromSharepointList Referencingnew_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromsharepointlist
	{
		get
		{
			return this.GetRelatedEntity<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromshar" +
					"epointlist", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingnew_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_esto" +
					"quefromsharepointlist");
			this.SetRelatedEntity<cr22f_EstoqueFromSharepointList>("new_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_estoquefromshar" +
					"epointlist", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingnew_cr22f_estoquefromsharepointlist_MercadoriaAnteriordoRMA_cr22f_esto" +
					"quefromsharepointlist");
		}
	}
}
#pragma warning restore CS1591
