#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Modelos de Produto From Sharepoint List
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr22f_modelosdeprodutofromsharepointlist_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Modelos de Produto From Sharepoint List
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr22f_modelosdeprodutofromsharepointlist_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cr22f_modelosdeprodutofromsharepointlist")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class cr22f_ModelosdeProdutoFromSharepointList : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public cr22f_ModelosdeProdutoFromSharepointList() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "cr22f_modelosdeprodutofromsharepointlist";
	
	public const string EntityLogicalCollectionName = "cr22f_modelosdeprodutofromsharepointlists";
	
	public const string EntitySetName = "cr22f_modelosdeprodutofromsharepointlists";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_categoriadeprodutoid")]
	public string cr22f_CategoriadeprodutoId
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_categoriadeprodutoid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_CategoriadeprodutoId");
			this.SetAttributeValue("cr22f_categoriadeprodutoid", value);
			this.OnPropertyChanged("cr22f_CategoriadeprodutoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_fabricanteid")]
	public string cr22f_FabricanteId
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_fabricanteid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_FabricanteId");
			this.SetAttributeValue("cr22f_fabricanteid", value);
			this.OnPropertyChanged("cr22f_FabricanteId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_horasagregadas")]
	public string cr22f_Horasagregadas
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_horasagregadas");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Horasagregadas");
			this.SetAttributeValue("cr22f_horasagregadas", value);
			this.OnPropertyChanged("cr22f_Horasagregadas");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_id")]
	public string cr22f_ID
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_id");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ID");
			this.SetAttributeValue("cr22f_id", value);
			this.OnPropertyChanged("cr22f_ID");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_modelosdeprodutofromsharepointlistid")]
	public System.Nullable<System.Guid> cr22f_ModelosdeProdutoFromSharepointListId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("cr22f_modelosdeprodutofromsharepointlistid");
		}
		set
		{
			this.OnPropertyChanging("cr22f_ModelosdeProdutoFromSharepointListId");
			this.SetAttributeValue("cr22f_modelosdeprodutofromsharepointlistid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("cr22f_ModelosdeProdutoFromSharepointListId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_modelosdeprodutofromsharepointlistid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.cr22f_ModelosdeProdutoFromSharepointListId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_modified")]
	public System.Nullable<System.DateTime> cr22f_Modified
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("cr22f_modified");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Modified");
			this.SetAttributeValue("cr22f_modified", value);
			this.OnPropertyChanged("cr22f_Modified");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_querycategoria")]
	public string cr22f_QueryCategoria
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_querycategoria");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryCategoria");
			this.SetAttributeValue("cr22f_querycategoria", value);
			this.OnPropertyChanged("cr22f_QueryCategoria");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_queryfabricante")]
	public string cr22f_QueryFabricante
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_queryfabricante");
		}
		set
		{
			this.OnPropertyChanging("cr22f_QueryFabricante");
			this.SetAttributeValue("cr22f_queryfabricante", value);
			this.OnPropertyChanged("cr22f_QueryFabricante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_title")]
	public string cr22f_Title
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_title");
		}
		set
		{
			this.OnPropertyChanging("cr22f_Title");
			this.SetAttributeValue("cr22f_title", value);
			this.OnPropertyChanged("cr22f_Title");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr22f_vendaaberta")]
	public string cr22f_VendaAberta
	{
		get
		{
			return this.GetAttributeValue<string>("cr22f_vendaaberta");
		}
		set
		{
			this.OnPropertyChanging("cr22f_VendaAberta");
			this.SetAttributeValue("cr22f_vendaaberta", value);
			this.OnPropertyChanged("cr22f_VendaAberta");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Exchange rate for the currency associated with the entity with respect to the base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_alturaminimaparainstalacaocm")]
	public System.Nullable<decimal> new_Alturaminimaparainstalacaocm
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_alturaminimaparainstalacaocm");
		}
		set
		{
			this.OnPropertyChanging("new_Alturaminimaparainstalacaocm");
			this.SetAttributeValue("new_alturaminimaparainstalacaocm", value);
			this.OnPropertyChanged("new_Alturaminimaparainstalacaocm");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_controlaetiqueta")]
	public System.Nullable<bool> new_ControlaEtiqueta
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_controlaetiqueta");
		}
		set
		{
			this.OnPropertyChanging("new_ControlaEtiqueta");
			this.SetAttributeValue("new_controlaetiqueta", value);
			this.OnPropertyChanged("new_ControlaEtiqueta");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_controlasn")]
	public System.Nullable<bool> new_ControlaSN
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_controlasn");
		}
		set
		{
			this.OnPropertyChanging("new_ControlaSN");
			this.SetAttributeValue("new_controlasn", value);
			this.OnPropertyChanged("new_ControlaSN");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricao")]
	public string new_Descricao
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricao");
		}
		set
		{
			this.OnPropertyChanging("new_Descricao");
			this.SetAttributeValue("new_descricao", value);
			this.OnPropertyChanged("new_Descricao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_deviceiotemplatejson")]
	public string new_DeviceIOTemplateJSON
	{
		get
		{
			return this.GetAttributeValue<string>("new_deviceiotemplatejson");
		}
		set
		{
			this.OnPropertyChanging("new_DeviceIOTemplateJSON");
			this.SetAttributeValue("new_deviceiotemplatejson", value);
			this.OnPropertyChanged("new_DeviceIOTemplateJSON");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_egranular")]
	public System.Nullable<bool> new_EGranular
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_egranular");
		}
		set
		{
			this.OnPropertyChanging("new_EGranular");
			this.SetAttributeValue("new_egranular", value);
			this.OnPropertyChanged("new_EGranular");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_estoqueabaixodominimo")]
	public System.Nullable<bool> new_EstoqueAbaixodoMinimo
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_estoqueabaixodominimo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fabricante")]
	public Microsoft.Xrm.Sdk.EntityReference new_Fabricante
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_fabricante");
		}
		set
		{
			this.OnPropertyChanging("new_Fabricante");
			this.SetAttributeValue("new_fabricante", value);
			this.OnPropertyChanged("new_Fabricante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grupodetrocalivredeprodutos")]
	public Microsoft.Xrm.Sdk.EntityReference new_GrupodeTrocaLivredeProdutos
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_grupodetrocalivredeprodutos");
		}
		set
		{
			this.OnPropertyChanging("new_GrupodeTrocaLivredeProdutos");
			this.SetAttributeValue("new_grupodetrocalivredeprodutos", value);
			this.OnPropertyChanged("new_GrupodeTrocaLivredeProdutos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_imagemdoprodutourl")]
	public string new_ImagemdoProdutoUrl
	{
		get
		{
			return this.GetAttributeValue<string>("new_imagemdoprodutourl");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_imagemdoprodutourlbase")]
	public string new_ImagemdoProdutoUrlBase
	{
		get
		{
			return this.GetAttributeValue<string>("new_imagemdoprodutourlbase");
		}
		set
		{
			this.OnPropertyChanging("new_ImagemdoProdutoUrlBase");
			this.SetAttributeValue("new_imagemdoprodutourlbase", value);
			this.OnPropertyChanged("new_ImagemdoProdutoUrlBase");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_indicedegarantiaextendidade1ano")]
	public System.Nullable<decimal> new_IndicedeGarantiaExtendidade1Ano
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_indicedegarantiaextendidade1ano");
		}
		set
		{
			this.OnPropertyChanging("new_IndicedeGarantiaExtendidade1Ano");
			this.SetAttributeValue("new_indicedegarantiaextendidade1ano", value);
			this.OnPropertyChanged("new_IndicedeGarantiaExtendidade1Ano");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_indicedegarantiaextendidade2anos")]
	public System.Nullable<decimal> new_IndicedeGarantiaExtendidade2Anos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_indicedegarantiaextendidade2anos");
		}
		set
		{
			this.OnPropertyChanging("new_IndicedeGarantiaExtendidade2Anos");
			this.SetAttributeValue("new_indicedegarantiaextendidade2anos", value);
			this.OnPropertyChanged("new_IndicedeGarantiaExtendidade2Anos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_indicedegarantiaextendidade3anos")]
	public System.Nullable<decimal> new_IndicedeGarantiaExtendidade3Anos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_indicedegarantiaextendidade3anos");
		}
		set
		{
			this.OnPropertyChanging("new_IndicedeGarantiaExtendidade3Anos");
			this.SetAttributeValue("new_indicedegarantiaextendidade3anos", value);
			this.OnPropertyChanged("new_IndicedeGarantiaExtendidade3Anos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_larguraminimaparainstalacaocm")]
	public System.Nullable<decimal> new_Larguraminimaparainstalacaocm
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_larguraminimaparainstalacaocm");
		}
		set
		{
			this.OnPropertyChanging("new_Larguraminimaparainstalacaocm");
			this.SetAttributeValue("new_larguraminimaparainstalacaocm", value);
			this.OnPropertyChanged("new_Larguraminimaparainstalacaocm");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_metrosporcaixacabos")]
	public System.Nullable<int> new_MetrosporCaixaCabos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_metrosporcaixacabos");
		}
		set
		{
			this.OnPropertyChanging("new_MetrosporCaixaCabos");
			this.SetAttributeValue("new_metrosporcaixacabos", value);
			this.OnPropertyChanged("new_MetrosporCaixaCabos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_modelodocabopormetrocaixadecabo")]
	public Microsoft.Xrm.Sdk.EntityReference new_ModelodoCaboporMetroCaixadeCabo
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_modelodocabopormetrocaixadecabo");
		}
		set
		{
			this.OnPropertyChanging("new_ModelodoCaboporMetroCaixadeCabo");
			this.SetAttributeValue("new_modelodocabopormetrocaixadecabo", value);
			this.OnPropertyChanged("new_ModelodoCaboporMetroCaixadeCabo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedofabricante")]
	public string new_NomedoFabricante
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedofabricante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedofornecedorprincipal")]
	public string new_NomedoFornecedorPrincipal
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedofornecedorprincipal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numericid")]
	public System.Nullable<int> new_NumericId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numericid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_omitirdoguiadeconexoes")]
	public System.Nullable<bool> new_OmitirdoGuiadeConexoes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_omitirdoguiadeconexoes");
		}
		set
		{
			this.OnPropertyChanging("new_OmitirdoGuiadeConexoes");
			this.SetAttributeValue("new_omitirdoguiadeconexoes", value);
			this.OnPropertyChanged("new_OmitirdoGuiadeConexoes");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_profundidademinimaparainstalacaocm")]
	public System.Nullable<decimal> new_Profundidademinimaparainstalacaocm
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_profundidademinimaparainstalacaocm");
		}
		set
		{
			this.OnPropertyChanging("new_Profundidademinimaparainstalacaocm");
			this.SetAttributeValue("new_profundidademinimaparainstalacaocm", value);
			this.OnPropertyChanged("new_Profundidademinimaparainstalacaocm");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedeestoqueminimo")]
	public System.Nullable<int> new_QuantidadedeEstoqueMinimo
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidadedeestoqueminimo");
		}
		set
		{
			this.OnPropertyChanging("new_QuantidadedeEstoqueMinimo");
			this.SetAttributeValue("new_quantidadedeestoqueminimo", value);
			this.OnPropertyChanged("new_QuantidadedeEstoqueMinimo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedisponivelemestoque")]
	public System.Nullable<int> new_QuantidadeDisponivelemEstoque
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidadedisponivelemestoque");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Quantidade Disponível em Estoque.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedisponivelemestoque_date")]
	public System.Nullable<System.DateTime> new_QuantidadeDisponivelemEstoque_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_quantidadedisponivelemestoque_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Quantidade Disponível em Estoque.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedisponivelemestoque_state")]
	public System.Nullable<int> new_QuantidadeDisponivelemEstoque_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidadedisponivelemestoque_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_requercabeamento")]
	public System.Nullable<bool> new_RequerCabeamento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_requercabeamento");
		}
		set
		{
			this.OnPropertyChanging("new_RequerCabeamento");
			this.SetAttributeValue("new_requercabeamento", value);
			this.OnPropertyChanged("new_RequerCabeamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_requerconfiguracao")]
	public System.Nullable<bool> new_RequerConfiguracao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_requerconfiguracao");
		}
		set
		{
			this.OnPropertyChanging("new_RequerConfiguracao");
			this.SetAttributeValue("new_requerconfiguracao", value);
			this.OnPropertyChanged("new_RequerConfiguracao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_requerengraving")]
	public System.Nullable<bool> new_RequerEngraving
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_requerengraving");
		}
		set
		{
			this.OnPropertyChanging("new_RequerEngraving");
			this.SetAttributeValue("new_requerengraving", value);
			this.OnPropertyChanged("new_RequerEngraving");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_reservadeprodutolivre")]
	public System.Nullable<bool> new_ReservadeProdutoLivre
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_reservadeprodutolivre");
		}
		set
		{
			this.OnPropertyChanging("new_ReservadeProdutoLivre");
			this.SetAttributeValue("new_reservadeprodutolivre", value);
			this.OnPropertyChanged("new_ReservadeProdutoLivre");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeospadrao")]
	public virtual new_tipodeservicodeos? new_TipodeOSPadrao
	{
		get
		{
			return ((new_tipodeservicodeos?)(EntityOptionSetEnum.GetEnum(this, "new_tipodeospadrao")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodesistemapadrao")]
	public virtual new_tipodesistema? new_TipodeSistemaPadrao
	{
		get
		{
			return ((new_tipodesistema?)(EntityOptionSetEnum.GetEnum(this, "new_tipodesistemapadrao")));
		}
		set
		{
			this.OnPropertyChanging("new_TipodeSistemaPadrao");
			this.SetAttributeValue("new_tipodesistemapadrao", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_TipodeSistemaPadrao");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Modelos de Produto From Sharepoint List
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual cr22f_modelosdeprodutofromsharepointlist_statecode? statecode
	{
		get
		{
			return ((cr22f_modelosdeprodutofromsharepointlist_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Modelos de Produto From Sharepoint List
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual cr22f_modelosdeprodutofromsharepointlist_statuscode? statuscode
	{
		get
		{
			return ((cr22f_modelosdeprodutofromsharepointlist_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the currency associated with the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N new_cr22f_modelosdeprodutofromsharepointlcbcx
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_modelosdeprodutofromsharepointlcbcx", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<cr22f_ModelosdeProdutoFromSharepointList> Referencednew_cr22f_modelosdeprodutofromsharepointlcbcx
	{
		get
		{
			return this.GetRelatedEntities<cr22f_ModelosdeProdutoFromSharepointList>("new_cr22f_modelosdeprodutofromsharepointlcbcx", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencednew_cr22f_modelosdeprodutofromsharepointlcbcx");
			this.SetRelatedEntities<cr22f_ModelosdeProdutoFromSharepointList>("new_cr22f_modelosdeprodutofromsharepointlcbcx", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencednew_cr22f_modelosdeprodutofromsharepointlcbcx");
		}
	}
	
	/// <summary>
	/// 1:N new_new_deviceio_ModelodeProduto_cr22f_modelo
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_deviceio_ModelodeProduto_cr22f_modelo")]
	public System.Collections.Generic.IEnumerable<new_DeviceIO> new_new_deviceio_ModelodeProduto_cr22f_modelo
	{
		get
		{
			return this.GetRelatedEntities<new_DeviceIO>("new_new_deviceio_ModelodeProduto_cr22f_modelo", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_deviceio_ModelodeProduto_cr22f_modelo");
			this.SetRelatedEntities<new_DeviceIO>("new_new_deviceio_ModelodeProduto_cr22f_modelo", null, value);
			this.OnPropertyChanged("new_new_deviceio_ModelodeProduto_cr22f_modelo");
		}
	}
	
	/// <summary>
	/// N:1 new_cr22f_modelosdeprodutofromsharepointlcbcx
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_modelodocabopormetrocaixadecabo")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_modelosdeprodutofromsharepointlcbcx", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public cr22f_ModelosdeProdutoFromSharepointList Referencingnew_cr22f_modelosdeprodutofromsharepointlcbcx
	{
		get
		{
			return this.GetRelatedEntity<cr22f_ModelosdeProdutoFromSharepointList>("new_cr22f_modelosdeprodutofromsharepointlcbcx", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingnew_cr22f_modelosdeprodutofromsharepointlcbcx");
			this.SetRelatedEntity<cr22f_ModelosdeProdutoFromSharepointList>("new_cr22f_modelosdeprodutofromsharepointlcbcx", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingnew_cr22f_modelosdeprodutofromsharepointlcbcx");
		}
	}
	
	/// <summary>
	/// N:1 new_cr22f_ModelosdeProdutoFromSharepointList_
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fabricante")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cr22f_ModelosdeProdutoFromSharepointList_")]
	public cr22f_FabricantesFromSharpointList new_cr22f_ModelosdeProdutoFromSharepointList_
	{
		get
		{
			return this.GetRelatedEntity<cr22f_FabricantesFromSharpointList>("new_cr22f_ModelosdeProdutoFromSharepointList_", null);
		}
		set
		{
			this.OnPropertyChanging("new_cr22f_ModelosdeProdutoFromSharepointList_");
			this.SetRelatedEntity<cr22f_FabricantesFromSharpointList>("new_cr22f_ModelosdeProdutoFromSharepointList_", null, value);
			this.OnPropertyChanged("new_cr22f_ModelosdeProdutoFromSharepointList_");
		}
	}
}
#pragma warning restore CS1591
