#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the TipoServiço-PreçodeProduto
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tiposervicoprecodeproduto_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the TipoServiço-PreçodeProduto
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tiposervicoprecodeproduto_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_tiposervicoprecodeproduto")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_TipoServicoPrecodeProduto : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_TipoServicoPrecodeProduto() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_tiposervicoprecodeproduto";
	
	public const string EntityLogicalCollectionName = "new_tiposervicoprecodeprodutos";
	
	public const string EntitySetName = "new_tiposervicoprecodeprodutos";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricaodoservico")]
	public string new_DescricaodoServico
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricaodoservico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_incluirnoorcamento")]
	public System.Nullable<bool> new_IncluirnoOrcamento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_incluirnoorcamento");
		}
		set
		{
			this.OnPropertyChanging("new_IncluirnoOrcamento");
			this.SetAttributeValue("new_incluirnoorcamento", value);
			this.OnPropertyChanged("new_IncluirnoOrcamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orcamento")]
	public Microsoft.Xrm.Sdk.EntityReference new_Orcamento
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_orcamento");
		}
		set
		{
			this.OnPropertyChanging("new_Orcamento");
			this.SetAttributeValue("new_orcamento", value);
			this.OnPropertyChanged("new_Orcamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_precodeproduto")]
	public Microsoft.Xrm.Sdk.EntityReference new_PrecodeProduto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_precodeproduto");
		}
		set
		{
			this.OnPropertyChanging("new_PrecodeProduto");
			this.SetAttributeValue("new_precodeproduto", value);
			this.OnPropertyChanged("new_PrecodeProduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_remocaopermitida")]
	public System.Nullable<bool> new_RemocaoPermitida
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_remocaopermitida");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_taxadeservicopercentualfinalfx")]
	public System.Nullable<decimal> new_TaxadeServicoPercentualFinalFx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_taxadeservicopercentualfinalfx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_taxafixafx")]
	public System.Nullable<decimal> new_TaxaFixaFx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_taxafixafx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_taxapercentualemcimadoservicofx")]
	public System.Nullable<decimal> new_TaxaPercentualemCimadoServicoFx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_taxapercentualemcimadoservicofx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_TipodeServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_tipodeservico");
		}
		set
		{
			this.OnPropertyChanging("new_TipodeServico");
			this.SetAttributeValue("new_tipodeservico", value);
			this.OnPropertyChanged("new_TipodeServico");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tiposervicoprecodeprodutoid")]
	public System.Nullable<System.Guid> new_TipoServicoPrecodeProdutoId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_tiposervicoprecodeprodutoid");
		}
		set
		{
			this.OnPropertyChanging("new_TipoServicoPrecodeProdutoId");
			this.SetAttributeValue("new_tiposervicoprecodeprodutoid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_TipoServicoPrecodeProdutoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tiposervicoprecodeprodutoid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_TipoServicoPrecodeProdutoId = value;
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the TipoServiço-PreçodeProduto
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_tiposervicoprecodeproduto_statecode? statecode
	{
		get
		{
			return ((new_tiposervicoprecodeproduto_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the TipoServiço-PreçodeProduto
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_tiposervicoprecodeproduto_statuscode? statuscode
	{
		get
		{
			return ((new_tiposervicoprecodeproduto_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
