#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the S3 Objects
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_s3objects_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the S3 Objects
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_s3objects_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_s3objects")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_S3Objects : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_S3Objects() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_s3objects";
	
	public const string EntityLogicalCollectionName = "new_s3objectses";
	
	public const string EntitySetName = "new_s3objectses";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_bucketname")]
	public string new_BucketName
	{
		get
		{
			return this.GetAttributeValue<string>("new_bucketname");
		}
		set
		{
			this.OnPropertyChanging("new_BucketName");
			this.SetAttributeValue("new_bucketname", value);
			this.OnPropertyChanged("new_BucketName");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_componentedescricaoitemcatalogoverificacao")]
	public Microsoft.Xrm.Sdk.EntityReference new_ComponenteDescricaoItemCatalogoVerificacao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_componentedescricaoitemcatalogoverificacao");
		}
		set
		{
			this.OnPropertyChanging("new_ComponenteDescricaoItemCatalogoVerificacao");
			this.SetAttributeValue("new_componentedescricaoitemcatalogoverificacao", value);
			this.OnPropertyChanged("new_ComponenteDescricaoItemCatalogoVerificacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datetime")]
	public System.Nullable<System.DateTime> new_DateTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datetime");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_feedbackdocolaborador")]
	public Microsoft.Xrm.Sdk.EntityReference new_FeedbackdoColaborador
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_feedbackdocolaborador");
		}
		set
		{
			this.OnPropertyChanging("new_FeedbackdoColaborador");
			this.SetAttributeValue("new_feedbackdocolaborador", value);
			this.OnPropertyChanged("new_FeedbackdoColaborador");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_isimage")]
	public System.Nullable<bool> new_IsImage
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_isimage");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_localurl")]
	public string new_LocalUrl
	{
		get
		{
			return this.GetAttributeValue<string>("new_localurl");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedocliente")]
	public string new_NomedoCliente
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedocliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedoprojeto")]
	public string new_NomedoProjeto
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedoprojeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedoremetente")]
	public string new_NomedoRemetente
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedoremetente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_ordemdeservico");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServico");
			this.SetAttributeValue("new_ordemdeservico", value);
			this.OnPropertyChanged("new_OrdemdeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_remoteurl")]
	public string new_RemoteUrl
	{
		get
		{
			return this.GetAttributeValue<string>("new_remoteurl");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rma")]
	public Microsoft.Xrm.Sdk.EntityReference new_RMA
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_rma");
		}
		set
		{
			this.OnPropertyChanging("new_RMA");
			this.SetAttributeValue("new_rma", value);
			this.OnPropertyChanged("new_RMA");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_s3objectsid")]
	public System.Nullable<System.Guid> new_S3ObjectsId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_s3objectsid");
		}
		set
		{
			this.OnPropertyChanging("new_S3ObjectsId");
			this.SetAttributeValue("new_s3objectsid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_S3ObjectsId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_s3objectsid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_S3ObjectsId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_userlocation")]
	public Microsoft.Xrm.Sdk.EntityReference new_UserLocation
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_userlocation");
		}
		set
		{
			this.OnPropertyChanging("new_UserLocation");
			this.SetAttributeValue("new_userlocation", value);
			this.OnPropertyChanged("new_UserLocation");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_wazzupchatid")]
	public string new_WazzupChatId
	{
		get
		{
			return this.GetAttributeValue<string>("new_wazzupchatid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_wazzupmessage")]
	public Microsoft.Xrm.Sdk.EntityReference new_WazzupMessage
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_wazzupmessage");
		}
		set
		{
			this.OnPropertyChanging("new_WazzupMessage");
			this.SetAttributeValue("new_wazzupmessage", value);
			this.OnPropertyChanged("new_WazzupMessage");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_wazzupmessagedatetime")]
	public System.Nullable<System.DateTime> new_WazzupMessageDateTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_wazzupmessagedatetime");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_wazzupmessagetext")]
	public string new_WazzupMessageText
	{
		get
		{
			return this.GetAttributeValue<string>("new_wazzupmessagetext");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the S3 Objects
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_s3objects_statecode? statecode
	{
		get
		{
			return ((new_s3objects_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the S3 Objects
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_s3objects_statuscode? statuscode
	{
		get
		{
			return ((new_s3objects_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
