#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Utilização de Crédito
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_utilizacaodecredito_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Utilização de Crédito
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_utilizacaodecredito_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_utilizacaodecredito")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_UtilizacaodeCredito : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_UtilizacaodeCredito() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_utilizacaodecredito";
	
	public const string EntityLogicalCollectionName = "new_utilizacaodecreditos";
	
	public const string EntitySetName = "new_utilizacaodecreditos";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Exchange rate for the currency associated with the entity with respect to the base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cliente")]
	public Microsoft.Xrm.Sdk.EntityReference new_Cliente
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_cliente");
		}
		set
		{
			this.OnPropertyChanging("new_Cliente");
			this.SetAttributeValue("new_cliente", value);
			this.OnPropertyChanged("new_Cliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_creditodeutilizacao")]
	public Microsoft.Xrm.Sdk.EntityReference new_CreditodeUtilizacao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_creditodeutilizacao");
		}
		set
		{
			this.OnPropertyChanging("new_CreditodeUtilizacao");
			this.SetAttributeValue("new_creditodeutilizacao", value);
			this.OnPropertyChanged("new_CreditodeUtilizacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodapropostaorcamento")]
	public string new_NumerodaPropostaOrcamento
	{
		get
		{
			return this.GetAttributeValue<string>("new_numerodapropostaorcamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orcamentodeutilizacao")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrcamentodeUtilizacao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_orcamentodeutilizacao");
		}
		set
		{
			this.OnPropertyChanging("new_OrcamentodeUtilizacao");
			this.SetAttributeValue("new_orcamentodeutilizacao", value);
			this.OnPropertyChanged("new_OrcamentodeUtilizacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeutilizacao")]
	public virtual new_tipodeutilizacaodecredito? new_TipodeUtilizacao
	{
		get
		{
			return ((new_tipodeutilizacaodecredito?)(EntityOptionSetEnum.GetEnum(this, "new_tipodeutilizacao")));
		}
		set
		{
			this.OnPropertyChanging("new_TipodeUtilizacao");
			this.SetAttributeValue("new_tipodeutilizacao", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_TipodeUtilizacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_utilizacaocancelada")]
	public System.Nullable<bool> new_UtilizacaoCancelada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_utilizacaocancelada");
		}
		set
		{
			this.OnPropertyChanging("new_UtilizacaoCancelada");
			this.SetAttributeValue("new_utilizacaocancelada", value);
			this.OnPropertyChanged("new_UtilizacaoCancelada");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_utilizacaodecreditoid")]
	public System.Nullable<System.Guid> new_UtilizacaodeCreditoId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_utilizacaodecreditoid");
		}
		set
		{
			this.OnPropertyChanging("new_UtilizacaodeCreditoId");
			this.SetAttributeValue("new_utilizacaodecreditoid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_UtilizacaodeCreditoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_utilizacaodecreditoid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_UtilizacaodeCreditoId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_utilizacaofirmada")]
	public System.Nullable<bool> new_UtilizacaoFirmada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_utilizacaofirmada");
		}
		set
		{
			this.OnPropertyChanging("new_UtilizacaoFirmada");
			this.SetAttributeValue("new_utilizacaofirmada", value);
			this.OnPropertyChanged("new_UtilizacaoFirmada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valorutilizado")]
	public Microsoft.Xrm.Sdk.Money new_ValorUtilizado
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valorutilizado");
		}
		set
		{
			this.OnPropertyChanging("new_ValorUtilizado");
			this.SetAttributeValue("new_valorutilizado", value);
			this.OnPropertyChanged("new_ValorUtilizado");
		}
	}
	
	/// <summary>
	/// Value of the Valor Utilizado in base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valorutilizado_base")]
	public Microsoft.Xrm.Sdk.Money new_valorutilizado_Base
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valorutilizado_base");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Utilização de Crédito
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_utilizacaodecredito_statecode? statecode
	{
		get
		{
			return ((new_utilizacaodecredito_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Utilização de Crédito
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_utilizacaodecredito_statuscode? statuscode
	{
		get
		{
			return ((new_utilizacaodecredito_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the currency associated with the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:1 new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_creditodeutilizacao")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente")]
	public new_CreditosdoCliente new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente
	{
		get
		{
			return this.GetRelatedEntity<new_CreditosdoCliente>("new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente", null);
		}
		set
		{
			this.OnPropertyChanging("new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente");
			this.SetRelatedEntity<new_CreditosdoCliente>("new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente", null, value);
			this.OnPropertyChanged("new_utilizacaodecredito_CreditodeUtilizacao_new_creditosdocliente");
		}
	}
	
	/// <summary>
	/// N:1 new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orcamentodeutilizacao")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento")]
	public new_Orcamento new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento
	{
		get
		{
			return this.GetRelatedEntity<new_Orcamento>("new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento", null);
		}
		set
		{
			this.OnPropertyChanging("new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento");
			this.SetRelatedEntity<new_Orcamento>("new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento", null, value);
			this.OnPropertyChanged("new_utilizacaodecredito_OrcamentodeUtilizacao_new_orcamento");
		}
	}
}
#pragma warning restore CS1591
