#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Atividade Field Control
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_atividadefieldcontrol_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Atividade Field Control
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_atividadefieldcontrol_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_atividadefieldcontrol")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_AtividadeFieldControl : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_AtividadeFieldControl() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_atividadefieldcontrol";
	
	public const string EntityLogicalCollectionName = "new_atividadefieldcontrols";
	
	public const string EntitySetName = "new_atividadefieldcontrols";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_agendamento")]
	public System.Nullable<System.DateTime> new_Agendamento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_agendamento");
		}
		set
		{
			this.OnPropertyChanging("new_Agendamento");
			this.SetAttributeValue("new_agendamento", value);
			this.OnPropertyChanged("new_Agendamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_agendamentoconfirmadocomcliente")]
	public System.Nullable<bool> new_AgendamentoConfirmadoComCliente
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_agendamentoconfirmadocomcliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_agendamentooriginal")]
	public System.Nullable<System.DateTime> new_AgendamentoOriginal
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_agendamentooriginal");
		}
		set
		{
			this.OnPropertyChanging("new_AgendamentoOriginal");
			this.SetAttributeValue("new_agendamentooriginal", value);
			this.OnPropertyChanged("new_AgendamentoOriginal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_agendamentouserlocaldate")]
	public System.Nullable<System.DateTime> new_AgendamentoUserLocalDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_agendamentouserlocaldate");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_apelidodoprojeto")]
	public string new_ApelidodoProjeto
	{
		get
		{
			return this.GetAttributeValue<string>("new_apelidodoprojeto");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_atividadefieldcontrolid")]
	public System.Nullable<System.Guid> new_AtividadeFieldControlId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_atividadefieldcontrolid");
		}
		set
		{
			this.OnPropertyChanging("new_AtividadeFieldControlId");
			this.SetAttributeValue("new_atividadefieldcontrolid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_AtividadeFieldControlId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_atividadefieldcontrolid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_AtividadeFieldControlId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_atualizacaodetipodeospendente")]
	public System.Nullable<bool> new_AtualizacaodeTipodeOSPendente
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_atualizacaodetipodeospendente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_avaliacaopendentedescricaoai")]
	public System.Nullable<bool> new_AvaliacaoPendenteDescricaoAI
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_avaliacaopendentedescricaoai");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cliente")]
	public string new_Cliente
	{
		get
		{
			return this.GetAttributeValue<string>("new_cliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clientefieldcontrolid")]
	public string new_ClienteFieldControlId
	{
		get
		{
			return this.GetAttributeValue<string>("new_clientefieldcontrolid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_colaboradorfieldcontrolid")]
	public string new_ColaboradorFieldControlId
	{
		get
		{
			return this.GetAttributeValue<string>("new_colaboradorfieldcontrolid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_colaboradorpuid")]
	public string new_ColaboradorPUID
	{
		get
		{
			return this.GetAttributeValue<string>("new_colaboradorpuid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_colaboradoruserid")]
	public System.Nullable<decimal> new_ColaboradorUserId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_colaboradoruserid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_completedat")]
	public System.Nullable<System.DateTime> new_completedAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_completedat");
		}
		set
		{
			this.OnPropertyChanging("new_completedAt");
			this.SetAttributeValue("new_completedat", value);
			this.OnPropertyChanged("new_completedAt");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_comprimentodedescricaodostatus")]
	public System.Nullable<decimal> new_ComprimentodeDescricaodoStatus
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_comprimentodedescricaodostatus");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_comprimentodedescricaodostatusespelho")]
	public System.Nullable<decimal> new_ComprimentodeDescricaodoStatusEspelho
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_comprimentodedescricaodostatusespelho");
		}
		set
		{
			this.OnPropertyChanging("new_ComprimentodeDescricaodoStatusEspelho");
			this.SetAttributeValue("new_comprimentodedescricaodostatusespelho", value);
			this.OnPropertyChanged("new_ComprimentodeDescricaodoStatusEspelho");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contemsiteomada")]
	public System.Nullable<bool> new_ContemSiteOmada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_contemsiteomada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datacontatoconfirmacaoagendamento")]
	public System.Nullable<System.DateTime> new_DataContatoConfirmacaoAgendamento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datacontatoconfirmacaoagendamento");
		}
		set
		{
			this.OnPropertyChanging("new_DataContatoConfirmacaoAgendamento");
			this.SetAttributeValue("new_datacontatoconfirmacaoagendamento", value);
			this.OnPropertyChanged("new_DataContatoConfirmacaoAgendamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadefinicaodoagendamento")]
	public System.Nullable<System.DateTime> new_DataDefinicaodoAgendamento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadefinicaodoagendamento");
		}
		set
		{
			this.OnPropertyChanging("new_DataDefinicaodoAgendamento");
			this.SetAttributeValue("new_datadefinicaodoagendamento", value);
			this.OnPropertyChanged("new_DataDefinicaodoAgendamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_dataultimocontatoposatendimento")]
	public System.Nullable<System.DateTime> new_DataUltimoContatoPosAtendimento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_dataultimocontatoposatendimento");
		}
		set
		{
			this.OnPropertyChanging("new_DataUltimoContatoPosAtendimento");
			this.SetAttributeValue("new_dataultimocontatoposatendimento", value);
			this.OnPropertyChanged("new_DataUltimoContatoPosAtendimento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricaoaprovada")]
	public System.Nullable<bool> new_DescricaoAprovada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_descricaoaprovada");
		}
		set
		{
			this.OnPropertyChanging("new_DescricaoAprovada");
			this.SetAttributeValue("new_descricaoaprovada", value);
			this.OnPropertyChanged("new_DescricaoAprovada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricaoaprovadareason")]
	public string new_DescricaoAprovadaReason
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricaoaprovadareason");
		}
		set
		{
			this.OnPropertyChanging("new_DescricaoAprovadaReason");
			this.SetAttributeValue("new_descricaoaprovadareason", value);
			this.OnPropertyChanged("new_DescricaoAprovadaReason");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricaodostatuseditadaai")]
	public string new_DescricaodoStatusEditadaAI
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricaodostatuseditadaai");
		}
		set
		{
			this.OnPropertyChanging("new_DescricaodoStatusEditadaAI");
			this.SetAttributeValue("new_descricaodostatuseditadaai", value);
			this.OnPropertyChanged("new_DescricaodoStatusEditadaAI");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricaoopenaimirror")]
	public string new_DescricaoOpenAIMirror
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricaoopenaimirror");
		}
		set
		{
			this.OnPropertyChanging("new_DescricaoOpenAIMirror");
			this.SetAttributeValue("new_descricaoopenaimirror", value);
			this.OnPropertyChanged("new_DescricaoOpenAIMirror");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_description")]
	public string new_description
	{
		get
		{
			return this.GetAttributeValue<string>("new_description");
		}
		set
		{
			this.OnPropertyChanging("new_description");
			this.SetAttributeValue("new_description", value);
			this.OnPropertyChanged("new_description");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_duracao")]
	public System.Nullable<int> new_Duracao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_duracao");
		}
		set
		{
			this.OnPropertyChanging("new_Duracao");
			this.SetAttributeValue("new_duracao", value);
			this.OnPropertyChanged("new_Duracao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_duracaotemporal")]
	public System.Nullable<int> new_DuracaoTemporal
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_duracaotemporal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eatividadedesenhodepti")]
	public System.Nullable<bool> new_EAtividadeDesenhodePTI
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_eatividadedesenhodepti");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_employee")]
	public Microsoft.Xrm.Sdk.EntityReference new_employee
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_employee");
		}
		set
		{
			this.OnPropertyChanging("new_employee");
			this.SetAttributeValue("new_employee", value);
			this.OnPropertyChanged("new_employee");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_estaatribuidoaocolaborador")]
	public System.Nullable<bool> new_EstaAtribuidoaoColaborador
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_estaatribuidoaocolaborador");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_feedbackevalido")]
	public System.Nullable<bool> new_FeedbackeValido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_feedbackevalido");
		}
		set
		{
			this.OnPropertyChanging("new_FeedbackeValido");
			this.SetAttributeValue("new_feedbackevalido", value);
			this.OnPropertyChanged("new_FeedbackeValido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_feedbackfoienviado")]
	public System.Nullable<bool> new_FeedbackFoiEnviado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_feedbackfoienviado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_finishlocation")]
	public Microsoft.Xrm.Sdk.EntityReference new_FinishLocation
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_finishlocation");
		}
		set
		{
			this.OnPropertyChanging("new_FinishLocation");
			this.SetAttributeValue("new_finishlocation", value);
			this.OnPropertyChanged("new_FinishLocation");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_finishlocationisvalid")]
	public System.Nullable<bool> new_FinishLocationIsValid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_finishlocationisvalid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_finishlocationoffsetdistancemeter")]
	public System.Nullable<decimal> new_FinishLocationOffsetDistanceMeter
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_finishlocationoffsetdistancemeter");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_identificadorordemdeservico")]
	public string new_IdentificadorOrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<string>("new_identificadorordemdeservico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_incluiremcampanha")]
	public System.Nullable<bool> new_IncluiremCampanha
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_incluiremcampanha");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_indicedeatrasomenormelhor")]
	public System.Nullable<int> new_IndicedeAtrasomenormelhor
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_indicedeatrasomenormelhor");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_isfuturescheduledate")]
	public System.Nullable<bool> new_IsFutureScheduleDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_isfuturescheduledate");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_mensagemdefeedback")]
	public Microsoft.Xrm.Sdk.EntityReference new_MensagemdeFeedback
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_mensagemdefeedback");
		}
		set
		{
			this.OnPropertyChanging("new_MensagemdeFeedback");
			this.SetAttributeValue("new_mensagemdefeedback", value);
			this.OnPropertyChanged("new_MensagemdeFeedback");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_mensagemdefeedbackdatetime")]
	public System.Nullable<System.DateTime> new_MensagemdeFeedbackDateTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_mensagemdefeedbackdatetime");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedocolaborador")]
	public string new_NomedoColaborador
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedocolaborador");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_ordemdeservico");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServico");
			this.SetAttributeValue("new_ordemdeservico", value);
			this.OnPropertyChanged("new_OrdemdeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservicofieldcontrolid")]
	public string new_OrdemdeServicoFieldControlId
	{
		get
		{
			return this.GetAttributeValue<string>("new_ordemdeservicofieldcontrolid");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServicoFieldControlId");
			this.SetAttributeValue("new_ordemdeservicofieldcontrolid", value);
			this.OnPropertyChanged("new_OrdemdeServicoFieldControlId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_pontualidade")]
	public System.Nullable<int> new_Pontualidade
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_pontualidade");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodefinalizacao")]
	public System.Nullable<System.DateTime> new_PrevisaodeFinalizacao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaodefinalizacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	public Microsoft.Xrm.Sdk.EntityReference new_Projeto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_projeto");
		}
		set
		{
			this.OnPropertyChanging("new_Projeto");
			this.SetAttributeValue("new_projeto", value);
			this.OnPropertyChanged("new_Projeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedeatividadesparaconclusao")]
	public System.Nullable<decimal> new_QuantidadedeAtividadesParaConclusao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_quantidadedeatividadesparaconclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacao")]
	public string new_Situacao
	{
		get
		{
			return this.GetAttributeValue<string>("new_situacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_startedat")]
	public System.Nullable<System.DateTime> new_startedAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_startedat");
		}
		set
		{
			this.OnPropertyChanging("new_startedAt");
			this.SetAttributeValue("new_startedat", value);
			this.OnPropertyChanged("new_startedAt");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_startlocation")]
	public Microsoft.Xrm.Sdk.EntityReference new_StartLocation
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_startlocation");
		}
		set
		{
			this.OnPropertyChanging("new_StartLocation");
			this.SetAttributeValue("new_startlocation", value);
			this.OnPropertyChanged("new_StartLocation");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_startlocationimageid")]
	public System.Nullable<decimal> new_StartLocationImageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_startlocationimageid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_startlocationisvalid")]
	public System.Nullable<bool> new_StartLocationIsValid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_startlocationisvalid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_startlocationoffsetdistancemeter")]
	public System.Nullable<decimal> new_StartLocationOffsetDistanceMeter
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_startlocationoffsetdistancemeter");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_status")]
	public string new_status
	{
		get
		{
			return this.GetAttributeValue<string>("new_status");
		}
		set
		{
			this.OnPropertyChanging("new_status");
			this.SetAttributeValue("new_status", value);
			this.OnPropertyChanged("new_status");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_statuscolorb")]
	public System.Nullable<decimal> new_StatusColorB
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_statuscolorb");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_statuscolorg")]
	public System.Nullable<decimal> new_StatusColorG
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_statuscolorg");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_statuscolorr")]
	public System.Nullable<decimal> new_StatusColorR
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_statuscolorr");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_statusdescription")]
	public string new_statusDescription
	{
		get
		{
			return this.GetAttributeValue<string>("new_statusdescription");
		}
		set
		{
			this.OnPropertyChanging("new_statusDescription");
			this.SetAttributeValue("new_statusdescription", value);
			this.OnPropertyChanged("new_statusDescription");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_statusoficial")]
	public string new_StatusOficial
	{
		get
		{
			return this.GetAttributeValue<string>("new_statusoficial");
		}
		set
		{
			this.OnPropertyChanging("new_StatusOficial");
			this.SetAttributeValue("new_statusoficial", value);
			this.OnPropertyChanged("new_StatusOficial");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tags")]
	public string new_Tags
	{
		get
		{
			return this.GetAttributeValue<string>("new_tags");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tarefasjson")]
	public string new_TarefasJSON
	{
		get
		{
			return this.GetAttributeValue<string>("new_tarefasjson");
		}
		set
		{
			this.OnPropertyChanging("new_TarefasJSON");
			this.SetAttributeValue("new_tarefasjson", value);
			this.OnPropertyChanged("new_TarefasJSON");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservico")]
	public virtual new_tipodeservicodeos? new_TipodeServico
	{
		get
		{
			return ((new_tipodeservicodeos?)(EntityOptionSetEnum.GetEnum(this, "new_tipodeservico")));
		}
		set
		{
			this.OnPropertyChanging("new_TipodeServico");
			this.SetAttributeValue("new_tipodeservico", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_TipodeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservicodefinido")]
	public System.Nullable<bool> new_TipodeServicoDefinido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_tipodeservicodefinido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservicotexto")]
	public string new_TipodeServicoTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_tipodeservicotexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_vinculodeprojetopendente")]
	public System.Nullable<bool> new_VinculodeProjetoPendente
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_vinculodeprojetopendente");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Atividade Field Control
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_atividadefieldcontrol_statecode? statecode
	{
		get
		{
			return ((new_atividadefieldcontrol_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Atividade Field Control
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_atividadefieldcontrol_statuscode? statuscode
	{
		get
		{
			return ((new_atividadefieldcontrol_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:1 new_new_atividadefieldcontrol_OrdemdeServico_
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_atividadefieldcontrol_OrdemdeServico_")]
	public new_OrdemdeServicoFieldControl new_new_atividadefieldcontrol_OrdemdeServico_
	{
		get
		{
			return this.GetRelatedEntity<new_OrdemdeServicoFieldControl>("new_new_atividadefieldcontrol_OrdemdeServico_", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_atividadefieldcontrol_OrdemdeServico_");
			this.SetRelatedEntity<new_OrdemdeServicoFieldControl>("new_new_atividadefieldcontrol_OrdemdeServico_", null, value);
			this.OnPropertyChanged("new_new_atividadefieldcontrol_OrdemdeServico_");
		}
	}
	
	/// <summary>
	/// N:1 new_new_atividadefieldcontrol_Projeto_cr22f_p
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_atividadefieldcontrol_Projeto_cr22f_p")]
	public cr22f_Projeto new_new_atividadefieldcontrol_Projeto_cr22f_p
	{
		get
		{
			return this.GetRelatedEntity<cr22f_Projeto>("new_new_atividadefieldcontrol_Projeto_cr22f_p", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_atividadefieldcontrol_Projeto_cr22f_p");
			this.SetRelatedEntity<cr22f_Projeto>("new_new_atividadefieldcontrol_Projeto_cr22f_p", null, value);
			this.OnPropertyChanged("new_new_atividadefieldcontrol_Projeto_cr22f_p");
		}
	}
}
#pragma warning restore CS1591
