#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the RMA
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_rma_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the RMA
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_rma_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_rma")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_RMA : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_RMA() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_rma";
	
	public const string EntityLogicalCollectionName = "new_rmas";
	
	public const string EntitySetName = "new_rmas";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Exchange rate for the currency associated with the entity with respect to the base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_assistenciatecnica")]
	public string new_AssistenciaTecnica
	{
		get
		{
			return this.GetAttributeValue<string>("new_assistenciatecnica");
		}
		set
		{
			this.OnPropertyChanging("new_AssistenciaTecnica");
			this.SetAttributeValue("new_assistenciatecnica", value);
			this.OnPropertyChanged("new_AssistenciaTecnica");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cliente")]
	public Microsoft.Xrm.Sdk.EntityReference new_Cliente
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_cliente");
		}
		set
		{
			this.OnPropertyChanging("new_Cliente");
			this.SetAttributeValue("new_cliente", value);
			this.OnPropertyChanged("new_Cliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clienteinformadosobreestagioatual")]
	public System.Nullable<bool> new_ClienteInformadoSobreEstagioAtual
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_clienteinformadosobreestagioatual");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_codigoderastreiodatransportadora")]
	public string new_CodigodeRastreiodaTransportadora
	{
		get
		{
			return this.GetAttributeValue<string>("new_codigoderastreiodatransportadora");
		}
		set
		{
			this.OnPropertyChanging("new_CodigodeRastreiodaTransportadora");
			this.SetAttributeValue("new_codigoderastreiodatransportadora", value);
			this.OnPropertyChanged("new_CodigodeRastreiodaTransportadora");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadolembrete")]
	public System.Nullable<System.DateTime> new_DatadoLembrete
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadolembrete");
		}
		set
		{
			this.OnPropertyChanging("new_DatadoLembrete");
			this.SetAttributeValue("new_datadolembrete", value);
			this.OnPropertyChanged("new_DatadoLembrete");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricao")]
	public string new_Descricao
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricao");
		}
		set
		{
			this.OnPropertyChanging("new_Descricao");
			this.SetAttributeValue("new_descricao", value);
			this.OnPropertyChanged("new_Descricao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_lembreteexpirado")]
	public System.Nullable<bool> new_LembreteExpirado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_lembreteexpirado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedoclientefx")]
	public string new_NomedoClienteFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedoclientefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_observacoes")]
	public string new_Observacoes
	{
		get
		{
			return this.GetAttributeValue<string>("new_observacoes");
		}
		set
		{
			this.OnPropertyChanging("new_Observacoes");
			this.SetAttributeValue("new_observacoes", value);
			this.OnPropertyChanged("new_Observacoes");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_ordemdeservico");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServico");
			this.SetAttributeValue("new_ordemdeservico", value);
			this.OnPropertyChanged("new_OrdemdeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_posicao")]
	public System.Nullable<int> new_Posicao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_posicao");
		}
		set
		{
			this.OnPropertyChanging("new_Posicao");
			this.SetAttributeValue("new_posicao", value);
			this.OnPropertyChanged("new_Posicao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodechegadanaassistencia")]
	public System.Nullable<System.DateTime> new_PrevisaodeChegadanaAssistencia
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaodechegadanaassistencia");
		}
		set
		{
			this.OnPropertyChanging("new_PrevisaodeChegadanaAssistencia");
			this.SetAttributeValue("new_previsaodechegadanaassistencia", value);
			this.OnPropertyChanged("new_PrevisaodeChegadanaAssistencia");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaoderetornodaassistencia")]
	public System.Nullable<System.DateTime> new_PrevisaodeRetornodaAssistencia
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaoderetornodaassistencia");
		}
		set
		{
			this.OnPropertyChanging("new_PrevisaodeRetornodaAssistencia");
			this.SetAttributeValue("new_previsaoderetornodaassistencia", value);
			this.OnPropertyChanged("new_PrevisaodeRetornodaAssistencia");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	public Microsoft.Xrm.Sdk.EntityReference new_Projeto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_projeto");
		}
		set
		{
			this.OnPropertyChanging("new_Projeto");
			this.SetAttributeValue("new_projeto", value);
			this.OnPropertyChanged("new_Projeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projetoapelidofx")]
	public string new_ProjetoApelidoFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_projetoapelidofx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidade")]
	public System.Nullable<int> new_Quantidade
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidade");
		}
		set
		{
			this.OnPropertyChanging("new_Quantidade");
			this.SetAttributeValue("new_quantidade", value);
			this.OnPropertyChanged("new_Quantidade");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaid")]
	public System.Nullable<System.Guid> new_RMAId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_rmaid");
		}
		set
		{
			this.OnPropertyChanging("new_RMAId");
			this.SetAttributeValue("new_rmaid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_RMAId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rmaid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_RMAId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_sinalizar")]
	public System.Nullable<bool> new_Sinalizar
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_sinalizar");
		}
		set
		{
			this.OnPropertyChanging("new_Sinalizar");
			this.SetAttributeValue("new_sinalizar", value);
			this.OnPropertyChanged("new_Sinalizar");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacao")]
	public virtual new_rmastage? new_Situacao
	{
		get
		{
			return ((new_rmastage?)(EntityOptionSetEnum.GetEnum(this, "new_situacao")));
		}
		set
		{
			this.OnPropertyChanging("new_Situacao");
			this.SetAttributeValue("new_situacao", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_Situacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacaonumerico")]
	public System.Nullable<decimal> new_SituacaoNumerico
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_situacaonumerico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipoderma")]
	public virtual new_tipoderma? new_TipodeRMA
	{
		get
		{
			return ((new_tipoderma?)(EntityOptionSetEnum.GetEnum(this, "new_tipoderma")));
		}
		set
		{
			this.OnPropertyChanging("new_TipodeRMA");
			this.SetAttributeValue("new_tipoderma", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_TipodeRMA");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_transportadora")]
	public Microsoft.Xrm.Sdk.EntityReference new_Transportadora
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_transportadora");
		}
		set
		{
			this.OnPropertyChanging("new_Transportadora");
			this.SetAttributeValue("new_transportadora", value);
			this.OnPropertyChanged("new_Transportadora");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ultimoestagioinformadoaocliente")]
	public virtual new_rmastage? new_UltimoEstagioInformadoaoCliente
	{
		get
		{
			return ((new_rmastage?)(EntityOptionSetEnum.GetEnum(this, "new_ultimoestagioinformadoaocliente")));
		}
		set
		{
			this.OnPropertyChanging("new_UltimoEstagioInformadoaoCliente");
			this.SetAttributeValue("new_ultimoestagioinformadoaocliente", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_UltimoEstagioInformadoaoCliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valordofretedeida")]
	public Microsoft.Xrm.Sdk.Money new_ValordoFretedeIda
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valordofretedeida");
		}
		set
		{
			this.OnPropertyChanging("new_ValordoFretedeIda");
			this.SetAttributeValue("new_valordofretedeida", value);
			this.OnPropertyChanged("new_ValordoFretedeIda");
		}
	}
	
	/// <summary>
	/// Value of the Valor do Frete de Ida in base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valordofretedeida_base")]
	public Microsoft.Xrm.Sdk.Money new_valordofretedeida_Base
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valordofretedeida_base");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valordofretedevolta")]
	public Microsoft.Xrm.Sdk.Money new_ValordoFretedeVolta
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valordofretedevolta");
		}
		set
		{
			this.OnPropertyChanging("new_ValordoFretedeVolta");
			this.SetAttributeValue("new_valordofretedevolta", value);
			this.OnPropertyChanged("new_ValordoFretedeVolta");
		}
	}
	
	/// <summary>
	/// Value of the Valor do Frete de Volta in base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valordofretedevolta_base")]
	public Microsoft.Xrm.Sdk.Money new_valordofretedevolta_Base
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valordofretedevolta_base");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valordoreparo")]
	public Microsoft.Xrm.Sdk.Money new_ValordoReparo
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valordoreparo");
		}
		set
		{
			this.OnPropertyChanging("new_ValordoReparo");
			this.SetAttributeValue("new_valordoreparo", value);
			this.OnPropertyChanged("new_ValordoReparo");
		}
	}
	
	/// <summary>
	/// Value of the Valor do Reparo in base currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_valordoreparo_base")]
	public Microsoft.Xrm.Sdk.Money new_valordoreparo_Base
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_valordoreparo_base");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the RMA
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_rma_statecode? statecode
	{
		get
		{
			return ((new_rma_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the RMA
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_rma_statuscode? statuscode
	{
		get
		{
			return ((new_rma_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the currency associated with the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N new_estoquerma_RMA_new_rma
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_estoquerma_RMA_new_rma")]
	public System.Collections.Generic.IEnumerable<new_EstoqueRMA> new_estoquerma_RMA_new_rma
	{
		get
		{
			return this.GetRelatedEntities<new_EstoqueRMA>("new_estoquerma_RMA_new_rma", null);
		}
		set
		{
			this.OnPropertyChanging("new_estoquerma_RMA_new_rma");
			this.SetRelatedEntities<new_EstoqueRMA>("new_estoquerma_RMA_new_rma", null, value);
			this.OnPropertyChanged("new_estoquerma_RMA_new_rma");
		}
	}
	
	/// <summary>
	/// N:1 new_rma_Cliente_contact
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cliente")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_rma_Cliente_contact")]
	public Contact new_rma_Cliente_contact
	{
		get
		{
			return this.GetRelatedEntity<Contact>("new_rma_Cliente_contact", null);
		}
		set
		{
			this.OnPropertyChanging("new_rma_Cliente_contact");
			this.SetRelatedEntity<Contact>("new_rma_Cliente_contact", null, value);
			this.OnPropertyChanged("new_rma_Cliente_contact");
		}
	}
}
#pragma warning restore CS1591
