#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Produto-Serviço
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_produtoservico_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Produto-Serviço
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_produtoservico_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_produtoservico")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_ProdutoServico : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_ProdutoServico() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_produtoservico";
	
	public const string EntityLogicalCollectionName = "new_produtoservicos";
	
	public const string EntitySetName = "new_produtoservicos";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_antecedenciadepedidosdias")]
	public System.Nullable<decimal> new_AntecedenciadePedidosDias
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_antecedenciadepedidosdias");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_apelidodoprojetofx")]
	public string new_ApelidodoProjetoFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_apelidodoprojetofx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_atividadecriacaoos")]
	public Microsoft.Xrm.Sdk.EntityReference new_AtividadeCriacaoOS
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_atividadecriacaoos");
		}
		set
		{
			this.OnPropertyChanging("new_AtividadeCriacaoOS");
			this.SetAttributeValue("new_atividadecriacaoos", value);
			this.OnPropertyChanged("new_AtividadeCriacaoOS");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cliente")]
	public Microsoft.Xrm.Sdk.EntityReference new_Cliente
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_cliente");
		}
		set
		{
			this.OnPropertyChanging("new_Cliente");
			this.SetAttributeValue("new_cliente", value);
			this.OnPropertyChanged("new_Cliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clienteatualizado")]
	public System.Nullable<bool> new_ClienteAtualizado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_clienteatualizado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clientefieldcontrolid")]
	public string new_ClienteFieldControlId
	{
		get
		{
			return this.GetAttributeValue<string>("new_clientefieldcontrolid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contemcotacao")]
	public System.Nullable<bool> new_ContemCotacao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_contemcotacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cotacao")]
	public Microsoft.Xrm.Sdk.EntityReference new_Cotacao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_cotacao");
		}
		set
		{
			this.OnPropertyChanging("new_Cotacao");
			this.SetAttributeValue("new_cotacao", value);
			this.OnPropertyChanged("new_Cotacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cotacaofornecedorfx")]
	public string new_CotacaoFornecedorFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_cotacaofornecedorfx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cotacaonamefx")]
	public string new_CotacaoNameFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_cotacaonamefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_dataconclusaoengraving")]
	public System.Nullable<System.DateTime> new_DataConclusaoEngraving
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_dataconclusaoengraving");
		}
		set
		{
			this.OnPropertyChanging("new_DataConclusaoEngraving");
			this.SetAttributeValue("new_dataconclusaoengraving", value);
			this.OnPropertyChanged("new_DataConclusaoEngraving");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_dataconfirmacaoagendamentoentrega")]
	public System.Nullable<System.DateTime> new_DataConfirmacaoAgendamentoEntrega
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_dataconfirmacaoagendamentoentrega");
		}
		set
		{
			this.OnPropertyChanging("new_DataConfirmacaoAgendamentoEntrega");
			this.SetAttributeValue("new_dataconfirmacaoagendamentoentrega", value);
			this.OnPropertyChanged("new_DataConfirmacaoAgendamentoEntrega");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaentrega")]
	public System.Nullable<System.DateTime> new_DatadaEntrega
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaentrega");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimasolicitacaodevinculo")]
	public System.Nullable<System.DateTime> new_DatadaUltimaSolicitacaodeVinculo
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimasolicitacaodevinculo");
		}
		set
		{
			this.OnPropertyChanging("new_DatadaUltimaSolicitacaodeVinculo");
			this.SetAttributeValue("new_datadaultimasolicitacaodevinculo", value);
			this.OnPropertyChanged("new_DatadaUltimaSolicitacaodeVinculo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricao")]
	public string new_Descricao
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_disponivelparavinculo")]
	public System.Nullable<bool> new_DisponivelparaVinculo
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_disponivelparavinculo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eemprestimo")]
	public System.Nullable<bool> new_EEmprestimo
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_eemprestimo");
		}
		set
		{
			this.OnPropertyChanging("new_EEmprestimo");
			this.SetAttributeValue("new_eemprestimo", value);
			this.OnPropertyChanged("new_EEmprestimo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_efetuarpedido")]
	public System.Nullable<bool> new_EfetuarPedido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_efetuarpedido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_elegivelatrocaporcaixa")]
	public System.Nullable<bool> new_ElegivelaTrocaPorCaixa
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_elegivelatrocaporcaixa");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_emprestimodevolvido")]
	public System.Nullable<bool> new_EmprestimoDevolvido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_emprestimodevolvido");
		}
		set
		{
			this.OnPropertyChanging("new_EmprestimoDevolvido");
			this.SetAttributeValue("new_emprestimodevolvido", value);
			this.OnPropertyChanged("new_EmprestimoDevolvido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregaproxima")]
	public System.Nullable<bool> new_EntregaProxima
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entregaproxima");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregue")]
	public System.Nullable<bool> new_Entregue
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entregue");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregueespelho")]
	public System.Nullable<bool> new_EntregueEspelho
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entregueespelho");
		}
		set
		{
			this.OnPropertyChanging("new_EntregueEspelho");
			this.SetAttributeValue("new_entregueespelho", value);
			this.OnPropertyChanged("new_EntregueEspelho");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregueoverride")]
	public System.Nullable<bool> new_EntregueOverride
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entregueoverride");
		}
		set
		{
			this.OnPropertyChanging("new_EntregueOverride");
			this.SetAttributeValue("new_entregueoverride", value);
			this.OnPropertyChanged("new_EntregueOverride");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fabricante")]
	public string new_Fabricante
	{
		get
		{
			return this.GetAttributeValue<string>("new_fabricante");
		}
		set
		{
			this.OnPropertyChanging("new_Fabricante");
			this.SetAttributeValue("new_fabricante", value);
			this.OnPropertyChanged("new_Fabricante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fornecedorprincipalid")]
	public string new_FornecedorPrincipalId
	{
		get
		{
			return this.GetAttributeValue<string>("new_fornecedorprincipalid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_habilitartarefaconfirmarentregaf1fx")]
	public System.Nullable<bool> new_HabilitarTarefaConfirmarEntregaF1Fx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_habilitartarefaconfirmarentregaf1fx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_habilitartarefaconfirmarentregaf2fx")]
	public System.Nullable<bool> new_HabilitarTarefaConfirmarEntregaF2Fx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_habilitartarefaconfirmarentregaf2fx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_habilitartarefaconfirmarentregaf3fx")]
	public System.Nullable<bool> new_HabilitarTarefaConfirmarEntregaF3Fx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_habilitartarefaconfirmarentregaf3fx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_horasagregadas")]
	public System.Nullable<decimal> new_HorasAgregadas
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_horasagregadas");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_identificadorordemdeservico")]
	public string new_IdentificadorOrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<string>("new_identificadorordemdeservico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_impressaoderecibo")]
	public Microsoft.Xrm.Sdk.EntityReference new_ImpressaodeRecibo
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_impressaoderecibo");
		}
		set
		{
			this.OnPropertyChanging("new_ImpressaodeRecibo");
			this.SetAttributeValue("new_impressaoderecibo", value);
			this.OnPropertyChanged("new_ImpressaodeRecibo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_itemautoorigem")]
	public Microsoft.Xrm.Sdk.EntityReference new_ItemAutoOrigem
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_itemautoorigem");
		}
		set
		{
			this.OnPropertyChanging("new_ItemAutoOrigem");
			this.SetAttributeValue("new_itemautoorigem", value);
			this.OnPropertyChanged("new_ItemAutoOrigem");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_itemdedevolucao")]
	public Microsoft.Xrm.Sdk.EntityReference new_ItemdeDevolucao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_itemdedevolucao");
		}
		set
		{
			this.OnPropertyChanging("new_ItemdeDevolucao");
			this.SetAttributeValue("new_itemdedevolucao", value);
			this.OnPropertyChanged("new_ItemdeDevolucao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_localizacao")]
	public string new_Localizacao
	{
		get
		{
			return this.GetAttributeValue<string>("new_localizacao");
		}
		set
		{
			this.OnPropertyChanging("new_Localizacao");
			this.SetAttributeValue("new_localizacao", value);
			this.OnPropertyChanged("new_Localizacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_modelodeprodutooriginal")]
	public Microsoft.Xrm.Sdk.EntityReference new_ModelodeProdutoOriginal
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_modelodeprodutooriginal");
		}
		set
		{
			this.OnPropertyChanging("new_ModelodeProdutoOriginal");
			this.SetAttributeValue("new_modelodeprodutooriginal", value);
			this.OnPropertyChanged("new_ModelodeProdutoOriginal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
	public string new_Name
	{
		get
		{
			return this.GetAttributeValue<string>("new_name");
		}
		set
		{
			this.OnPropertyChanging("new_Name");
			this.SetAttributeValue("new_name", value);
			this.OnPropertyChanged("new_Name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedoclientefx")]
	public string new_NomedoClienteFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedoclientefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedofabricante")]
	public string new_NomedoFabricante
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedofabricante");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedofabricantev2")]
	public string new_NomedoFabricanteV2
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedofabricantev2");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedofornecedorprincipal")]
	public string new_NomedoFornecedorPrincipal
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedofornecedorprincipal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeentregaspendentes")]
	public System.Nullable<int> new_NumerodeEntregasPendentes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeentregaspendentes");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeprodutosentregues")]
	public System.Nullable<int> new_NumerodeProdutosEntregues
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeprodutosentregues");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Produtos Entregues.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeprodutosentregues_date")]
	public System.Nullable<System.DateTime> new_NumerodeProdutosEntregues_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodeprodutosentregues_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Produtos Entregues.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeprodutosentregues_state")]
	public System.Nullable<int> new_NumerodeProdutosEntregues_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeprodutosentregues_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeprodutosreservados")]
	public System.Nullable<int> new_NumerodeProdutosReservados
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeprodutosreservados");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Produtos Reservados.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeprodutosreservados_date")]
	public System.Nullable<System.DateTime> new_NumerodeProdutosReservados_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodeprodutosreservados_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Produtos Reservados.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeprodutosreservados_state")]
	public System.Nullable<int> new_NumerodeProdutosReservados_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeprodutosreservados_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_observacoesdopedido")]
	public string new_ObservacoesdoPedido
	{
		get
		{
			return this.GetAttributeValue<string>("new_observacoesdopedido");
		}
		set
		{
			this.OnPropertyChanging("new_ObservacoesdoPedido");
			this.SetAttributeValue("new_observacoesdopedido", value);
			this.OnPropertyChanged("new_ObservacoesdoPedido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_opcaodedevolucao")]
	public virtual new_opcaodedevolucao? new_OpcaodeDevolucao
	{
		get
		{
			return ((new_opcaodedevolucao?)(EntityOptionSetEnum.GetEnum(this, "new_opcaodedevolucao")));
		}
		set
		{
			this.OnPropertyChanging("new_OpcaodeDevolucao");
			this.SetAttributeValue("new_opcaodedevolucao", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_OpcaodeDevolucao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_opcaodeentrega")]
	public virtual new_opcaodeentrega? new_OpcaodeEntrega
	{
		get
		{
			return ((new_opcaodeentrega?)(EntityOptionSetEnum.GetEnum(this, "new_opcaodeentrega")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_opcaodefornecimento")]
	public virtual new_opcaodefornecimento? new_OpcaodeFornecimento
	{
		get
		{
			return ((new_opcaodefornecimento?)(EntityOptionSetEnum.GetEnum(this, "new_opcaodefornecimento")));
		}
		set
		{
			this.OnPropertyChanging("new_OpcaodeFornecimento");
			this.SetAttributeValue("new_opcaodefornecimento", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_OpcaodeFornecimento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orcamentodevolucao")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrcamentoDevolucao
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_orcamentodevolucao");
		}
		set
		{
			this.OnPropertyChanging("new_OrcamentoDevolucao");
			this.SetAttributeValue("new_orcamentodevolucao", value);
			this.OnPropertyChanged("new_OrcamentoDevolucao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	public Microsoft.Xrm.Sdk.EntityReference new_OrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_ordemdeservico");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServico");
			this.SetAttributeValue("new_ordemdeservico", value);
			this.OnPropertyChanged("new_OrdemdeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservicocontemprojeto")]
	public System.Nullable<bool> new_OrdemdeServicoContemProjeto
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_ordemdeservicocontemprojeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_pedidoefetuado")]
	public System.Nullable<bool> new_PedidoEfetuado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_pedidoefetuado");
		}
		set
		{
			this.OnPropertyChanging("new_PedidoEfetuado");
			this.SetAttributeValue("new_pedidoefetuado", value);
			this.OnPropertyChanged("new_PedidoEfetuado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_pedidopendente")]
	public System.Nullable<bool> new_PedidoPendente
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_pedidopendente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prazoconfirmentregaantespedido")]
	public System.Nullable<System.DateTime> new_PrazoConfirmEntregaAntesPedido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_prazoconfirmentregaantespedido");
		}
	}
	
	/// <summary>
	/// Data da tarefa para confirmação de agendamento da semana seguinte
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prazoconfirmentregasemanaseguinte")]
	public System.Nullable<System.DateTime> new_PrazoConfirmEntregaSemanaSeguinte
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_prazoconfirmentregasemanaseguinte");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prazodeenvio")]
	public virtual new_prazodeenviodemercadoria? new_PrazodeEnvio
	{
		get
		{
			return ((new_prazodeenviodemercadoria?)(EntityOptionSetEnum.GetEnum(this, "new_prazodeenvio")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodeentrega")]
	public System.Nullable<System.DateTime> new_PrevisaodeEntrega
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaodeentrega");
		}
		set
		{
			this.OnPropertyChanging("new_PrevisaodeEntrega");
			this.SetAttributeValue("new_previsaodeentrega", value);
			this.OnPropertyChanged("new_PrevisaodeEntrega");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodeentregadiadasemana")]
	public System.Nullable<int> new_PrevisaodeEntregaDiadaSemana
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_previsaodeentregadiadasemana");
		}
		set
		{
			this.OnPropertyChanging("new_PrevisaodeEntregaDiadaSemana");
			this.SetAttributeValue("new_previsaodeentregadiadasemana", value);
			this.OnPropertyChanged("new_PrevisaodeEntregaDiadaSemana");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodeentregav2fx")]
	public System.Nullable<System.DateTime> new_PrevisaodeEntregaV2Fx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaodeentregav2fx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodeenvio")]
	public System.Nullable<System.DateTime> new_PrevisaodeEnvio
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaodeenvio");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_produto")]
	public Microsoft.Xrm.Sdk.EntityReference new_Produto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_produto");
		}
		set
		{
			this.OnPropertyChanging("new_Produto");
			this.SetAttributeValue("new_produto", value);
			this.OnPropertyChanged("new_Produto");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_produtoservicoid")]
	public System.Nullable<System.Guid> new_ProdutoServicoId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_produtoservicoid");
		}
		set
		{
			this.OnPropertyChanging("new_ProdutoServicoId");
			this.SetAttributeValue("new_produtoservicoid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_ProdutoServicoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_produtoservicoid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_ProdutoServicoId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_produtotrocadodiferentedooriginal")]
	public System.Nullable<bool> new_ProdutoTrocadoDiferentedoOriginal
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_produtotrocadodiferentedooriginal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	public Microsoft.Xrm.Sdk.EntityReference new_Projeto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_projeto");
		}
		set
		{
			this.OnPropertyChanging("new_Projeto");
			this.SetAttributeValue("new_projeto", value);
			this.OnPropertyChanged("new_Projeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projetoatualizado")]
	public System.Nullable<bool> new_ProjetoAtualizado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_projetoatualizado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidade")]
	public System.Nullable<int> new_Quantidade
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidade");
		}
		set
		{
			this.OnPropertyChanging("new_Quantidade");
			this.SetAttributeValue("new_quantidade", value);
			this.OnPropertyChanged("new_Quantidade");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadeparapedir")]
	public System.Nullable<decimal> new_QuantidadeParaPedir
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_quantidadeparapedir");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_referenciadoproduto")]
	public string new_ReferenciadoProduto
	{
		get
		{
			return this.GetAttributeValue<string>("new_referenciadoproduto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_remessa")]
	public Microsoft.Xrm.Sdk.EntityReference new_Remessa
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_remessa");
		}
		set
		{
			this.OnPropertyChanging("new_Remessa");
			this.SetAttributeValue("new_remessa", value);
			this.OnPropertyChanged("new_Remessa");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_reservaefetuada")]
	public System.Nullable<bool> new_ReservaEfetuada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_reservaefetuada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_reservaefetuadaespelho")]
	public System.Nullable<bool> new_ReservaEfetuadaEspelho
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_reservaefetuadaespelho");
		}
		set
		{
			this.OnPropertyChanging("new_ReservaEfetuadaEspelho");
			this.SetAttributeValue("new_reservaefetuadaespelho", value);
			this.OnPropertyChanged("new_ReservaEfetuadaEspelho");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_reservagranular")]
	public System.Nullable<bool> new_ReservaGranular
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_reservagranular");
		}
		set
		{
			this.OnPropertyChanging("new_ReservaGranular");
			this.SetAttributeValue("new_reservagranular", value);
			this.OnPropertyChanged("new_ReservaGranular");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_separado")]
	public System.Nullable<bool> new_Separado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_separado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacaoreserva")]
	public virtual new_estadodoestoque? new_SituacaoReserva
	{
		get
		{
			return ((new_estadodoestoque?)(EntityOptionSetEnum.GetEnum(this, "new_situacaoreserva")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacaoreservatagcolorfx")]
	public string new_SituacaoReservaTagColorFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_situacaoreservatagcolorfx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacaoreservatextofx")]
	public string new_SituacaoReservaTextoFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_situacaoreservatextofx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_solicitacaodeimpressao3d")]
	public Microsoft.Xrm.Sdk.EntityReference new_SolicitacaodeImpressao3D
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_solicitacaodeimpressao3d");
		}
		set
		{
			this.OnPropertyChanging("new_SolicitacaodeImpressao3D");
			this.SetAttributeValue("new_solicitacaodeimpressao3d", value);
			this.OnPropertyChanged("new_SolicitacaodeImpressao3D");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tempodeservico")]
	public System.Nullable<int> new_TempodeServico
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_tempodeservico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_temporestanteparavinculominutos")]
	public System.Nullable<int> new_TempoRestanteparaVinculominutos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_temporestanteparavinculominutos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodesistemacontabilizadoos")]
	public System.Nullable<bool> new_TipodeSistemaContabilizadoOS
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_tipodesistemacontabilizadoos");
		}
		set
		{
			this.OnPropertyChanging("new_TipodeSistemaContabilizadoOS");
			this.SetAttributeValue("new_tipodesistemacontabilizadoos", value);
			this.OnPropertyChanged("new_TipodeSistemaContabilizadoOS");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Produto-Serviço
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_produtoservico_statecode? statecode
	{
		get
		{
			return ((new_produtoservico_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Produto-Serviço
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_produtoservico_statuscode? statuscode
	{
		get
		{
			return ((new_produtoservico_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:1 new_new_produtoservico_OrdemdeServico_new_ord
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservico")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_produtoservico_OrdemdeServico_new_ord")]
	public new_OrdemdeServicoFieldControl new_new_produtoservico_OrdemdeServico_new_ord
	{
		get
		{
			return this.GetRelatedEntity<new_OrdemdeServicoFieldControl>("new_new_produtoservico_OrdemdeServico_new_ord", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_produtoservico_OrdemdeServico_new_ord");
			this.SetRelatedEntity<new_OrdemdeServicoFieldControl>("new_new_produtoservico_OrdemdeServico_new_ord", null, value);
			this.OnPropertyChanged("new_new_produtoservico_OrdemdeServico_new_ord");
		}
	}
	
	/// <summary>
	/// N:1 new_new_produtoservico_Projeto_cr22f_projeto
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_produtoservico_Projeto_cr22f_projeto")]
	public cr22f_Projeto new_new_produtoservico_Projeto_cr22f_projeto
	{
		get
		{
			return this.GetRelatedEntity<cr22f_Projeto>("new_new_produtoservico_Projeto_cr22f_projeto", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_produtoservico_Projeto_cr22f_projeto");
			this.SetRelatedEntity<cr22f_Projeto>("new_new_produtoservico_Projeto_cr22f_projeto", null, value);
			this.OnPropertyChanged("new_new_produtoservico_Projeto_cr22f_projeto");
		}
	}
}
#pragma warning restore CS1591
