#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Ordem de Serviço Field Control
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_ordemdeservicofieldcontrol_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Ordem de Serviço Field Control
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_ordemdeservicofieldcontrol_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_ordemdeservicofieldcontrol")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class new_OrdemdeServicoFieldControl : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public new_OrdemdeServicoFieldControl() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "new_ordemdeservicofieldcontrol";
	
	public const string EntityLogicalCollectionName = "new_ordemdeservicofieldcontrols";
	
	public const string EntitySetName = "new_ordemdeservicofieldcontrols";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_anotacao")]
	public string new_Anotacao
	{
		get
		{
			return this.GetAttributeValue<string>("new_anotacao");
		}
		set
		{
			this.OnPropertyChanging("new_Anotacao");
			this.SetAttributeValue("new_anotacao", value);
			this.OnPropertyChanged("new_Anotacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_antecedenciadepedidosdias")]
	public System.Nullable<decimal> new_AntecedenciadePedidosDias
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_antecedenciadepedidosdias");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_aprovacaofinalizacaoid")]
	public string new_AprovacaoFinalizacaoId
	{
		get
		{
			return this.GetAttributeValue<string>("new_aprovacaofinalizacaoid");
		}
		set
		{
			this.OnPropertyChanging("new_AprovacaoFinalizacaoId");
			this.SetAttributeValue("new_aprovacaofinalizacaoid", value);
			this.OnPropertyChanged("new_AprovacaoFinalizacaoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_aprovacaofinalizacaostatus")]
	public virtual cr22f_aprovacaotatus? new_AprovacaoFinalizacaoStatus
	{
		get
		{
			return ((cr22f_aprovacaotatus?)(EntityOptionSetEnum.GetEnum(this, "new_aprovacaofinalizacaostatus")));
		}
		set
		{
			this.OnPropertyChanging("new_AprovacaoFinalizacaoStatus");
			this.SetAttributeValue("new_aprovacaofinalizacaostatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_AprovacaoFinalizacaoStatus");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_arquitetodoprojetofx")]
	public string new_ArquitetodoProjetoFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_arquitetodoprojetofx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cliente")]
	public Microsoft.Xrm.Sdk.EntityReference new_Cliente
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_cliente");
		}
		set
		{
			this.OnPropertyChanging("new_Cliente");
			this.SetAttributeValue("new_cliente", value);
			this.OnPropertyChanged("new_Cliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clienteid")]
	public string new_ClienteId
	{
		get
		{
			return this.GetAttributeValue<string>("new_clienteid");
		}
		set
		{
			this.OnPropertyChanging("new_ClienteId");
			this.SetAttributeValue("new_clienteid", value);
			this.OnPropertyChanged("new_ClienteId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_clientenome")]
	public string new_ClienteNome
	{
		get
		{
			return this.GetAttributeValue<string>("new_clientenome");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_concluido")]
	public System.Nullable<bool> new_Concluido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_concluido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_conclusao")]
	public string new_Conclusao
	{
		get
		{
			return this.GetAttributeValue<string>("new_conclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contadordepesquisasdesatisfacao")]
	public System.Nullable<int> new_ContadordePesquisasdeSatisfacao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_contadordepesquisasdesatisfacao");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Contador de Pesquisas de Satisfação.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contadordepesquisasdesatisfacao_date")]
	public System.Nullable<System.DateTime> new_ContadordePesquisasdeSatisfacao_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_contadordepesquisasdesatisfacao_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Contador de Pesquisas de Satisfação.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contadordepesquisasdesatisfacao_state")]
	public System.Nullable<int> new_ContadordePesquisasdeSatisfacao_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_contadordepesquisasdesatisfacao_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_coordenador")]
	public Microsoft.Xrm.Sdk.EntityReference new_Coordenador
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_coordenador");
		}
		set
		{
			this.OnPropertyChanging("new_Coordenador");
			this.SetAttributeValue("new_coordenador", value);
			this.OnPropertyChanged("new_Coordenador");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_createdbyfullnamefx")]
	public string new_CreatedByFullNameFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_createdbyfullnamefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_criadordoprojetofullnamefx")]
	public string new_CriadordoProjetoFullNameFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_criadordoprojetofullnamefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaconferenciaantesdainstalacao")]
	public System.Nullable<System.DateTime> new_DatadaConferenciaAntesdaInstalacao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaconferenciaantesdainstalacao");
		}
		set
		{
			this.OnPropertyChanging("new_DatadaConferenciaAntesdaInstalacao");
			this.SetAttributeValue("new_datadaconferenciaantesdainstalacao", value);
			this.OnPropertyChanged("new_DatadaConferenciaAntesdaInstalacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaprimeiraatividadefinalizada")]
	public System.Nullable<System.DateTime> new_DatadaPrimeiraAtividadeFinalizada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaprimeiraatividadefinalizada");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Data da Primeira Atividade Finalizada.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaprimeiraatividadefinalizada_date")]
	public System.Nullable<System.DateTime> new_DatadaPrimeiraAtividadeFinalizada_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaprimeiraatividadefinalizada_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Data da Primeira Atividade Finalizada.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaprimeiraatividadefinalizada_state")]
	public System.Nullable<int> new_DatadaPrimeiraAtividadeFinalizada_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_datadaprimeiraatividadefinalizada_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaproximaatividade")]
	public System.Nullable<System.DateTime> new_DatadaProximaAtividade
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaproximaatividade");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Data da Próxima Atividade.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaproximaatividade_date")]
	public System.Nullable<System.DateTime> new_DatadaProximaAtividade_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaproximaatividade_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Data da Próxima Atividade.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaproximaatividade_state")]
	public System.Nullable<int> new_DatadaProximaAtividade_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_datadaproximaatividade_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaalteracaodeprevisao")]
	public System.Nullable<System.DateTime> new_DatadaUltimaAlteracaodePrevisao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaalteracaodeprevisao");
		}
		set
		{
			this.OnPropertyChanging("new_DatadaUltimaAlteracaodePrevisao");
			this.SetAttributeValue("new_datadaultimaalteracaodeprevisao", value);
			this.OnPropertyChanged("new_DatadaUltimaAlteracaodePrevisao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaatividade")]
	public System.Nullable<System.DateTime> new_DatadaUltimaAtividade
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaatividade");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Data da Última Atividade.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaatividade_date")]
	public System.Nullable<System.DateTime> new_DatadaUltimaAtividade_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaatividade_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Data da Última Atividade.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaatividade_state")]
	public System.Nullable<int> new_DatadaUltimaAtividade_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_datadaultimaatividade_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaatividadefinalizada")]
	public System.Nullable<System.DateTime> new_DatadaUltimaAtividadeFinalizada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaatividadefinalizada");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Data da Última Atividade Finalizada.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaatividadefinalizada_date")]
	public System.Nullable<System.DateTime> new_DatadaUltimaAtividadeFinalizada_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaatividadefinalizada_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Data da Última Atividade Finalizada.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaatividadefinalizada_state")]
	public System.Nullable<int> new_DatadaUltimaAtividadeFinalizada_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_datadaultimaatividadefinalizada_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimaconferenciadecabeamentoexecutada")]
	public System.Nullable<System.DateTime> new_DatadaUltimaConferenciadeCabeamentoExecutada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimaconferenciadecabeamentoexecutada");
		}
		set
		{
			this.OnPropertyChanging("new_DatadaUltimaConferenciadeCabeamentoExecutada");
			this.SetAttributeValue("new_datadaultimaconferenciadecabeamentoexecutada", value);
			this.OnPropertyChanged("new_DatadaUltimaConferenciadeCabeamentoExecutada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadaultimatentativadecontato")]
	public System.Nullable<System.DateTime> new_DatadaUltimaTentativadeContato
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadaultimatentativadecontato");
		}
		set
		{
			this.OnPropertyChanging("new_DatadaUltimaTentativadeContato");
			this.SetAttributeValue("new_datadaultimatentativadecontato", value);
			this.OnPropertyChanged("new_DatadaUltimaTentativadeContato");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadeconclusao")]
	public System.Nullable<System.DateTime> new_DatadeConclusao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadeconclusao");
		}
		set
		{
			this.OnPropertyChanging("new_DatadeConclusao");
			this.SetAttributeValue("new_datadeconclusao", value);
			this.OnPropertyChanged("new_DatadeConclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadeconclusaodoguiadeconexoesfx")]
	public System.Nullable<System.DateTime> new_DatadeConclusaodoGuiadeConexoesFx
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadeconclusaodoguiadeconexoesfx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadedefinicaoconclusao")]
	public System.Nullable<System.DateTime> new_DatadeDefinicaoConclusao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadedefinicaoconclusao");
		}
		set
		{
			this.OnPropertyChanging("new_DatadeDefinicaoConclusao");
			this.SetAttributeValue("new_datadedefinicaoconclusao", value);
			this.OnPropertyChanged("new_DatadeDefinicaoConclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datademontagemdoquadro")]
	public System.Nullable<System.DateTime> new_DatadeMontagemdoQuadro
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datademontagemdoquadro");
		}
		set
		{
			this.OnPropertyChanging("new_DatadeMontagemdoQuadro");
			this.SetAttributeValue("new_datademontagemdoquadro", value);
			this.OnPropertyChanged("new_DatadeMontagemdoQuadro");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadepublicacao")]
	public System.Nullable<System.DateTime> new_DatadePublicacao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadepublicacao");
		}
		set
		{
			this.OnPropertyChanging("new_DatadePublicacao");
			this.SetAttributeValue("new_datadepublicacao", value);
			this.OnPropertyChanged("new_DatadePublicacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadoprimeiroenviodeprojeto")]
	public System.Nullable<System.DateTime> new_DatadoPrimeiroEnviodeProjeto
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadoprimeiroenviodeprojeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadoultimochecklistexecutado")]
	public System.Nullable<System.DateTime> new_DatadoUltimoChecklistExecutado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadoultimochecklistexecutado");
		}
		set
		{
			this.OnPropertyChanging("new_DatadoUltimoChecklistExecutado");
			this.SetAttributeValue("new_datadoultimochecklistexecutado", value);
			this.OnPropertyChanged("new_DatadoUltimoChecklistExecutado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadoultimocomentariodeordemdeservico")]
	public System.Nullable<System.DateTime> new_DatadoUltimoComentariodeOrdemdeServico
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadoultimocomentariodeordemdeservico");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Data do Último Comentário de Ordem de Serviço.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadoultimocomentariodeordemdeservico_date")]
	public System.Nullable<System.DateTime> new_DatadoUltimoComentariodeOrdemdeServico_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_datadoultimocomentariodeordemdeservico_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Data do Último Comentário de Ordem de Serviço.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_datadoultimocomentariodeordemdeservico_state")]
	public System.Nullable<int> new_DatadoUltimoComentariodeOrdemdeServico_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_datadoultimocomentariodeordemdeservico_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_defaultlocation")]
	public Microsoft.Xrm.Sdk.EntityReference new_DefaultLocation
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_defaultlocation");
		}
		set
		{
			this.OnPropertyChanging("new_DefaultLocation");
			this.SetAttributeValue("new_defaultlocation", value);
			this.OnPropertyChanged("new_DefaultLocation");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_defaultlocationimageid")]
	public System.Nullable<decimal> new_DefaultLocationImageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_defaultlocationimageid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_dentrodameta")]
	public System.Nullable<bool> new_DentrodaMeta
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_dentrodameta");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_descricao")]
	public string new_Descricao
	{
		get
		{
			return this.GetAttributeValue<string>("new_descricao");
		}
		set
		{
			this.OnPropertyChanging("new_Descricao");
			this.SetAttributeValue("new_descricao", value);
			this.OnPropertyChanged("new_Descricao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_diasparaconclusao")]
	public System.Nullable<int> new_DiasParaConclusao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_diasparaconclusao");
		}
		set
		{
			this.OnPropertyChanging("new_DiasParaConclusao");
			this.SetAttributeValue("new_diasparaconclusao", value);
			this.OnPropertyChanged("new_DiasParaConclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_emaildocliente")]
	public string new_EmaildoCliente
	{
		get
		{
			return this.GetAttributeValue<string>("new_emaildocliente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enderecocep")]
	public string new_EnderecoCEP
	{
		get
		{
			return this.GetAttributeValue<string>("new_enderecocep");
		}
		set
		{
			this.OnPropertyChanging("new_EnderecoCEP");
			this.SetAttributeValue("new_enderecocep", value);
			this.OnPropertyChanged("new_EnderecoCEP");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enderecocidade")]
	public string new_EnderecoCidade
	{
		get
		{
			return this.GetAttributeValue<string>("new_enderecocidade");
		}
		set
		{
			this.OnPropertyChanging("new_EnderecoCidade");
			this.SetAttributeValue("new_enderecocidade", value);
			this.OnPropertyChanged("new_EnderecoCidade");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enderecocomplemento")]
	public string new_EnderecoComplemento
	{
		get
		{
			return this.GetAttributeValue<string>("new_enderecocomplemento");
		}
		set
		{
			this.OnPropertyChanging("new_EnderecoComplemento");
			this.SetAttributeValue("new_enderecocomplemento", value);
			this.OnPropertyChanged("new_EnderecoComplemento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enderecocompletofx")]
	public string new_EnderecoCompletoFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_enderecocompletofx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enderecorua")]
	public string new_EnderecoRua
	{
		get
		{
			return this.GetAttributeValue<string>("new_enderecorua");
		}
		set
		{
			this.OnPropertyChanging("new_EnderecoRua");
			this.SetAttributeValue("new_enderecorua", value);
			this.OnPropertyChanged("new_EnderecoRua");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregaconfirmada")]
	public System.Nullable<bool> new_Entregaconfirmada
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entregaconfirmada");
		}
		set
		{
			this.OnPropertyChanging("new_Entregaconfirmada");
			this.SetAttributeValue("new_entregaconfirmada", value);
			this.OnPropertyChanged("new_Entregaconfirmada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregaconfirmadaicon")]
	public string new_EntregaConfirmadaIcon
	{
		get
		{
			return this.GetAttributeValue<string>("new_entregaconfirmadaicon");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregaconfirmadaiconcolor")]
	public string new_EntregaConfirmadaIconColor
	{
		get
		{
			return this.GetAttributeValue<string>("new_entregaconfirmadaiconcolor");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregaconfirmadanumber")]
	public System.Nullable<int> new_EntregaConfirmadaNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_entregaconfirmadanumber");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entregue")]
	public System.Nullable<bool> new_Entregue
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entregue");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entreguebase")]
	public System.Nullable<bool> new_EntregueBase
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_entreguebase");
		}
		set
		{
			this.OnPropertyChanging("new_EntregueBase");
			this.SetAttributeValue("new_entreguebase", value);
			this.OnPropertyChanged("new_EntregueBase");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_flag")]
	public System.Nullable<int> new_Flag
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_flag");
		}
		set
		{
			this.OnPropertyChanging("new_Flag");
			this.SetAttributeValue("new_flag", value);
			this.OnPropertyChanged("new_Flag");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_id")]
	public string new_Id
	{
		get
		{
			return this.GetAttributeValue<string>("new_id");
		}
		set
		{
			this.OnPropertyChanging("new_Id");
			this.SetAttributeValue("new_id", value);
			this.OnPropertyChanged("new_Id");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ignorarlocalizacao")]
	public System.Nullable<bool> new_IgnorarLocalizacao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_ignorarlocalizacao");
		}
		set
		{
			this.OnPropertyChanging("new_IgnorarLocalizacao");
			this.SetAttributeValue("new_ignorarlocalizacao", value);
			this.OnPropertyChanged("new_IgnorarLocalizacao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_incluiremagendamentosemanal")]
	public System.Nullable<bool> new_IncluiremAgendamentoSemanal
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_incluiremagendamentosemanal");
		}
		set
		{
			this.OnPropertyChanging("new_IncluiremAgendamentoSemanal");
			this.SetAttributeValue("new_incluiremagendamentosemanal", value);
			this.OnPropertyChanged("new_IncluiremAgendamentoSemanal");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_issubmitted")]
	public System.Nullable<bool> new_IsSubmitted
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_issubmitted");
		}
		set
		{
			this.OnPropertyChanging("new_IsSubmitted");
			this.SetAttributeValue("new_issubmitted", value);
			this.OnPropertyChanged("new_IsSubmitted");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_latitudebase")]
	public System.Nullable<decimal> new_LatitudeBase
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_latitudebase");
		}
		set
		{
			this.OnPropertyChanging("new_LatitudeBase");
			this.SetAttributeValue("new_latitudebase", value);
			this.OnPropertyChanged("new_LatitudeBase");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_liberadopreagendamentoentrega")]
	public System.Nullable<bool> new_Liberadopreagendamentoentrega
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_liberadopreagendamentoentrega");
		}
		set
		{
			this.OnPropertyChanging("new_Liberadopreagendamentoentrega");
			this.SetAttributeValue("new_liberadopreagendamentoentrega", value);
			this.OnPropertyChanged("new_Liberadopreagendamentoentrega");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_localizacaoid")]
	public string new_LocalizacaoId
	{
		get
		{
			return this.GetAttributeValue<string>("new_localizacaoid");
		}
		set
		{
			this.OnPropertyChanging("new_LocalizacaoId");
			this.SetAttributeValue("new_localizacaoid", value);
			this.OnPropertyChanged("new_LocalizacaoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_localizacaopendente")]
	public System.Nullable<bool> new_LocalizacaoPendente
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_localizacaopendente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_locationlatitude")]
	public System.Nullable<decimal> new_LocationLatitude
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_locationlatitude");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_locationlongitude")]
	public System.Nullable<decimal> new_LocationLongitude
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_locationlongitude");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_locationoffsetcustomtolerancemeters")]
	public System.Nullable<int> new_LocationOffsetCustomToleranceMeters
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_locationoffsetcustomtolerancemeters");
		}
		set
		{
			this.OnPropertyChanging("new_LocationOffsetCustomToleranceMeters");
			this.SetAttributeValue("new_locationoffsetcustomtolerancemeters", value);
			this.OnPropertyChanged("new_LocationOffsetCustomToleranceMeters");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_locationoffsettolerancemeters")]
	public System.Nullable<decimal> new_LocationOffsetToleranceMeters
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_locationoffsettolerancemeters");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_longitudebase")]
	public System.Nullable<decimal> new_LongitudeBase
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_longitudebase");
		}
		set
		{
			this.OnPropertyChanging("new_LongitudeBase");
			this.SetAttributeValue("new_longitudebase", value);
			this.OnPropertyChanged("new_LongitudeBase");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_metacalculadaautomaticamente")]
	public System.Nullable<bool> new_MetaCalculadaAutomaticamente
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_metacalculadaautomaticamente");
		}
		set
		{
			this.OnPropertyChanging("new_MetaCalculadaAutomaticamente");
			this.SetAttributeValue("new_metacalculadaautomaticamente", value);
			this.OnPropertyChanged("new_MetaCalculadaAutomaticamente");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_metadenumerodeatividades")]
	public System.Nullable<int> new_MetadeNumerodeAtividades
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_metadenumerodeatividades");
		}
		set
		{
			this.OnPropertyChanging("new_MetadeNumerodeAtividades");
			this.SetAttributeValue("new_metadenumerodeatividades", value);
			this.OnPropertyChanged("new_MetadeNumerodeAtividades");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_modifiedbyfullnamefx")]
	public string new_ModifiedByFullNameFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_modifiedbyfullnamefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
	public string new_Name
	{
		get
		{
			return this.GetAttributeValue<string>("new_name");
		}
		set
		{
			this.OnPropertyChanging("new_Name");
			this.SetAttributeValue("new_name", value);
			this.OnPropertyChanged("new_Name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_nomedoclientefx")]
	public string new_NomedoClienteFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_nomedoclientefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeatividadescadastradas")]
	public System.Nullable<int> new_NumerodeAtividadesCadastradas
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeatividadescadastradas");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Atividades Cadastradas.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeatividadescadastradas_date")]
	public System.Nullable<System.DateTime> new_NumerodeAtividadesCadastradas_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodeatividadescadastradas_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Atividades Cadastradas.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeatividadescadastradas_state")]
	public System.Nullable<int> new_NumerodeAtividadesCadastradas_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeatividadescadastradas_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeatividadesrealizadas")]
	public System.Nullable<int> new_NumerodeAtividadesRealizadas
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeatividadesrealizadas");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Atividades Realizadas.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeatividadesrealizadas_date")]
	public System.Nullable<System.DateTime> new_NumerodeAtividadesRealizadas_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodeatividadesrealizadas_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Atividades Realizadas.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeatividadesrealizadas_state")]
	public System.Nullable<int> new_NumerodeAtividadesRealizadas_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeatividadesrealizadas_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeentregaspendentes")]
	public System.Nullable<int> new_NumerodeEntregasPendentes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeentregaspendentes");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Entregas Pendentes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeentregaspendentes_date")]
	public System.Nullable<System.DateTime> new_NumerodeEntregasPendentes_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodeentregaspendentes_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Entregas Pendentes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodeentregaspendentes_state")]
	public System.Nullable<int> new_NumerodeEntregasPendentes_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodeentregaspendentes_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodepedidos")]
	public System.Nullable<int> new_NumerodePedidos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodepedidos");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Pedidos.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodepedidos_date")]
	public System.Nullable<System.DateTime> new_NumerodePedidos_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodepedidos_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Pedidos.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodepedidos_state")]
	public System.Nullable<int> new_NumerodePedidos_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodepedidos_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodepedidosdeprodutospendentes")]
	public System.Nullable<int> new_NumerodePedidosdeProdutosPendentes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodepedidosdeprodutospendentes");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Pedidos de Produtos Pendentes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodepedidosdeprodutospendentes_date")]
	public System.Nullable<System.DateTime> new_NumerodePedidosdeProdutosPendentes_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodepedidosdeprodutospendentes_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Pedidos de Produtos Pendentes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodepedidosdeprodutospendentes_state")]
	public System.Nullable<int> new_NumerodePedidosdeProdutosPendentes_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodepedidosdeprodutospendentes_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodereservaspendentes")]
	public System.Nullable<int> new_NumerodeReservasPendentes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodereservaspendentes");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número de Reservas Pendentes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodereservaspendentes_date")]
	public System.Nullable<System.DateTime> new_NumerodeReservasPendentes_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerodereservaspendentes_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número de Reservas Pendentes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerodereservaspendentes_state")]
	public System.Nullable<int> new_NumerodeReservasPendentes_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerodereservaspendentes_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerototaldeprodutos")]
	public System.Nullable<int> new_NumeroTotaldeProdutos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerototaldeprodutos");
		}
	}
	
	/// <summary>
	/// Last Updated time of rollup field Número Total de Produtos.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerototaldeprodutos_date")]
	public System.Nullable<System.DateTime> new_NumeroTotaldeProdutos_Date
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_numerototaldeprodutos_date");
		}
	}
	
	/// <summary>
	/// State of rollup field Número Total de Produtos.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numerototaldeprodutos_state")]
	public System.Nullable<int> new_NumeroTotaldeProdutos_State
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_numerototaldeprodutos_state");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_onradar")]
	public System.Nullable<bool> new_OnRadar
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_onradar");
		}
		set
		{
			this.OnPropertyChanging("new_OnRadar");
			this.SetAttributeValue("new_onradar", value);
			this.OnPropertyChanged("new_OnRadar");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orcamento")]
	public Microsoft.Xrm.Sdk.EntityReference new_Orcamento
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_orcamento");
		}
		set
		{
			this.OnPropertyChanging("new_Orcamento");
			this.SetAttributeValue("new_orcamento", value);
			this.OnPropertyChanged("new_Orcamento");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservicofieldcontrolid")]
	public System.Nullable<System.Guid> new_OrdemdeServicoFieldControlId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_ordemdeservicofieldcontrolid");
		}
		set
		{
			this.OnPropertyChanging("new_OrdemdeServicoFieldControlId");
			this.SetAttributeValue("new_ordemdeservicofieldcontrolid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_OrdemdeServicoFieldControlId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ordemdeservicofieldcontrolid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_OrdemdeServicoFieldControlId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_percentualdeconclusao")]
	public System.Nullable<decimal> new_PercentualdeConclusao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("new_percentualdeconclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_percentualdereservaprodutos")]
	public string new_PercentualdeReservaProdutos
	{
		get
		{
			return this.GetAttributeValue<string>("new_percentualdereservaprodutos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prazoconfirmentregaantespedido")]
	public System.Nullable<System.DateTime> new_PrazoConfirmEntregaAntesPedido
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_prazoconfirmentregaantespedido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_prazodeenviodoprojeto")]
	public System.Nullable<System.DateTime> new_Prazodeenviodoprojeto
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_prazodeenviodoprojeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodeentregadosprodutos")]
	public System.Nullable<System.DateTime> new_PrevisaodeEntregadosProdutos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_previsaodeentregadosprodutos");
		}
		set
		{
			this.OnPropertyChanging("new_PrevisaodeEntregadosProdutos");
			this.SetAttributeValue("new_previsaodeentregadosprodutos", value);
			this.OnPropertyChanged("new_PrevisaodeEntregadosProdutos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_previsaodeentregadosprodutosdiadasemana")]
	public System.Nullable<int> new_PrevisaodeEntregadosProdutosDiadaSemana
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_previsaodeentregadosprodutosdiadasemana");
		}
		set
		{
			this.OnPropertyChanging("new_PrevisaodeEntregadosProdutosDiadaSemana");
			this.SetAttributeValue("new_previsaodeentregadosprodutosdiadasemana", value);
			this.OnPropertyChanged("new_PrevisaodeEntregadosProdutosDiadaSemana");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	public Microsoft.Xrm.Sdk.EntityReference new_Projeto
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_projeto");
		}
		set
		{
			this.OnPropertyChanging("new_Projeto");
			this.SetAttributeValue("new_projeto", value);
			this.OnPropertyChanged("new_Projeto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projetoapelido")]
	public string new_ProjetoApelido
	{
		get
		{
			return this.GetAttributeValue<string>("new_projetoapelido");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_publicado")]
	public System.Nullable<bool> new_Publicado
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_publicado");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_publicadopor")]
	public Microsoft.Xrm.Sdk.EntityReference new_PublicadoPor
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_publicadopor");
		}
		set
		{
			this.OnPropertyChanging("new_PublicadoPor");
			this.SetAttributeValue("new_publicadopor", value);
			this.OnPropertyChanged("new_PublicadoPor");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_publicadoporfullnamefx")]
	public string new_PublicadoPorFullNameFx
	{
		get
		{
			return this.GetAttributeValue<string>("new_publicadoporfullnamefx");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedeatividadesparaconclusao")]
	public System.Nullable<int> new_QuantidadedeAtividadesParaConclusao
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidadedeatividadesparaconclusao");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_quantidadedecabos")]
	public System.Nullable<int> new_QuantidadedeCabos
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_quantidadedecabos");
		}
		set
		{
			this.OnPropertyChanging("new_QuantidadedeCabos");
			this.SetAttributeValue("new_quantidadedecabos", value);
			this.OnPropertyChanged("new_QuantidadedeCabos");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_requeratualizacaodecoordenador")]
	public System.Nullable<bool> new_RequerAtualizacaodeCoordenador
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_requeratualizacaodecoordenador");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_resumo")]
	public string new_Resumo
	{
		get
		{
			return this.GetAttributeValue<string>("new_resumo");
		}
		set
		{
			this.OnPropertyChanging("new_Resumo");
			this.SetAttributeValue("new_resumo", value);
			this.OnPropertyChanged("new_Resumo");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_resumodate")]
	public System.Nullable<System.DateTime> new_ResumoDATE
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_resumodate");
		}
		set
		{
			this.OnPropertyChanging("new_ResumoDATE");
			this.SetAttributeValue("new_resumodate", value);
			this.OnPropertyChanged("new_ResumoDATE");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_resumopendencias")]
	public string new_Resumopendencias
	{
		get
		{
			return this.GetAttributeValue<string>("new_resumopendencias");
		}
		set
		{
			this.OnPropertyChanging("new_Resumopendencias");
			this.SetAttributeValue("new_resumopendencias", value);
			this.OnPropertyChanged("new_Resumopendencias");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_resumopendenciasdate")]
	public System.Nullable<System.DateTime> new_ResumopendenciasDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_resumopendenciasdate");
		}
		set
		{
			this.OnPropertyChanging("new_ResumopendenciasDate");
			this.SetAttributeValue("new_resumopendenciasdate", value);
			this.OnPropertyChanged("new_ResumopendenciasDate");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_semrespostapreagendamento")]
	public System.Nullable<bool> new_SemRespostaPreAgendamento
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_semrespostapreagendamento");
		}
		set
		{
			this.OnPropertyChanging("new_SemRespostaPreAgendamento");
			this.SetAttributeValue("new_semrespostapreagendamento", value);
			this.OnPropertyChanged("new_SemRespostaPreAgendamento");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_servicoid")]
	public string new_ServicoId
	{
		get
		{
			return this.GetAttributeValue<string>("new_servicoid");
		}
		set
		{
			this.OnPropertyChanging("new_ServicoId");
			this.SetAttributeValue("new_servicoid", value);
			this.OnPropertyChanged("new_ServicoId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacaodeprodutos")]
	public virtual new_estadodoestoque? new_SituacaodeProdutos
	{
		get
		{
			return ((new_estadodoestoque?)(EntityOptionSetEnum.GetEnum(this, "new_situacaodeprodutos")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_situacaodeprodutostagcolor")]
	public string new_SituacaodeProdutosTagColor
	{
		get
		{
			return this.GetAttributeValue<string>("new_situacaodeprodutostagcolor");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tecnicositeomada")]
	public Microsoft.Xrm.Sdk.EntityReference new_TecnicoSiteOmada
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_tecnicositeomada");
		}
		set
		{
			this.OnPropertyChanging("new_TecnicoSiteOmada");
			this.SetAttributeValue("new_tecnicositeomada", value);
			this.OnPropertyChanged("new_TecnicoSiteOmada");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservico")]
	public virtual new_tipodeservicodeos? new_TipodeServico
	{
		get
		{
			return ((new_tipodeservicodeos?)(EntityOptionSetEnum.GetEnum(this, "new_tipodeservico")));
		}
		set
		{
			this.OnPropertyChanging("new_TipodeServico");
			this.SetAttributeValue("new_tipodeservico", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("new_TipodeServico");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservicotagcolor")]
	public string new_TipodeServicoTagColor
	{
		get
		{
			return this.GetAttributeValue<string>("new_tipodeservicotagcolor");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tipodeservicotexto")]
	public string new_TipodeServicoTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_tipodeservicotexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_tiposdesistematexto")]
	public string new_TiposdeSistemaTexto
	{
		get
		{
			return this.GetAttributeValue<string>("new_tiposdesistematexto");
		}
		set
		{
			this.OnPropertyChanging("new_TiposdeSistemaTexto");
			this.SetAttributeValue("new_tiposdesistematexto", value);
			this.OnPropertyChanged("new_TiposdeSistemaTexto");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_ultimaatividadedetarefa")]
	public string new_UltimaAtividadedeTarefa
	{
		get
		{
			return this.GetAttributeValue<string>("new_ultimaatividadedetarefa");
		}
		set
		{
			this.OnPropertyChanging("new_UltimaAtividadedeTarefa");
			this.SetAttributeValue("new_ultimaatividadedetarefa", value);
			this.OnPropertyChanged("new_UltimaAtividadedeTarefa");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_urlparaobterarquivos")]
	public string new_UrlParaObterArquivos
	{
		get
		{
			return this.GetAttributeValue<string>("new_urlparaobterarquivos");
		}
		set
		{
			this.OnPropertyChanging("new_UrlParaObterArquivos");
			this.SetAttributeValue("new_urlparaobterarquivos", value);
			this.OnPropertyChanged("new_UrlParaObterArquivos");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Ordem de Serviço Field Control
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual new_ordemdeservicofieldcontrol_statecode? statecode
	{
		get
		{
			return ((new_ordemdeservicofieldcontrol_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Ordem de Serviço Field Control
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual new_ordemdeservicofieldcontrol_statuscode? statuscode
	{
		get
		{
			return ((new_ordemdeservicofieldcontrol_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N new_new_atividadefieldcontrol_OrdemdeServico_
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_atividadefieldcontrol_OrdemdeServico_")]
	public System.Collections.Generic.IEnumerable<new_AtividadeFieldControl> new_new_atividadefieldcontrol_OrdemdeServico_
	{
		get
		{
			return this.GetRelatedEntities<new_AtividadeFieldControl>("new_new_atividadefieldcontrol_OrdemdeServico_", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_atividadefieldcontrol_OrdemdeServico_");
			this.SetRelatedEntities<new_AtividadeFieldControl>("new_new_atividadefieldcontrol_OrdemdeServico_", null, value);
			this.OnPropertyChanged("new_new_atividadefieldcontrol_OrdemdeServico_");
		}
	}
	
	/// <summary>
	/// 1:N new_new_produtoservico_OrdemdeServico_new_ord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_produtoservico_OrdemdeServico_new_ord")]
	public System.Collections.Generic.IEnumerable<new_ProdutoServico> new_new_produtoservico_OrdemdeServico_new_ord
	{
		get
		{
			return this.GetRelatedEntities<new_ProdutoServico>("new_new_produtoservico_OrdemdeServico_new_ord", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_produtoservico_OrdemdeServico_new_ord");
			this.SetRelatedEntities<new_ProdutoServico>("new_new_produtoservico_OrdemdeServico_new_ord", null, value);
			this.OnPropertyChanged("new_new_produtoservico_OrdemdeServico_new_ord");
		}
	}
	
	/// <summary>
	/// N:1 new_new_ordemdeservicofieldcontrol_Projeto_cr
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_projeto")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_ordemdeservicofieldcontrol_Projeto_cr")]
	public cr22f_Projeto new_new_ordemdeservicofieldcontrol_Projeto_cr
	{
		get
		{
			return this.GetRelatedEntity<cr22f_Projeto>("new_new_ordemdeservicofieldcontrol_Projeto_cr", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_ordemdeservicofieldcontrol_Projeto_cr");
			this.SetRelatedEntity<cr22f_Projeto>("new_new_ordemdeservicofieldcontrol_Projeto_cr", null, value);
			this.OnPropertyChanged("new_new_ordemdeservicofieldcontrol_Projeto_cr");
		}
	}
}
#pragma warning restore CS1591
