#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum cr22f_aprovacaotatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Solicitado = 538780000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Aprovado = 538780001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Rejeitado = 538780002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancelado = 538780003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Revogado = 538780004,
}
#pragma warning restore CS1591
