#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_modalidadedepagamento
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Vista = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Parcelado = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Financiamento = 100000002,
}
#pragma warning restore CS1591
