#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tipodeservicodeos
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cabeamento = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Instalao = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Manuteno = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Confernciadeinfraestrutura = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Entrega = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	DesenhodePTI = 100000005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	AjustedePTI = 100000006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Instalaoplacadeobra = 100000007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Remoodeplacadeobra = 100000008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	MontagemdeQuadro = 100000009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ServioInterno = 100000010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ListadeConferncia = 100000011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Configurao = 100000012,
}
#pragma warning restore CS1591
