#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_rmastage
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Novos = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emavaliaointerna = 101000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Enviarparaassistncia = 101100000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emtrnsitoparaassistncia = 102000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emanlise = 103000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Aguardandoaprovao = 104000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emreparo = 105000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emtrnsitoderetorno = 106000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Recebidodaassistncia = 107000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Testado = 108000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Devolvido = 109000000,
}
#pragma warning restore CS1591
