#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tipoderma
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	RetornoTemporrioaoEstoque = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Manuteno = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	DevoluoDefinitivadoProduto = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	DevoluodeEmprstimo = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	RetornoParaTrocadeProduto = 100000004,
}
#pragma warning restore CS1591
