#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tipodesistema
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Automao = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	udio = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Vdeo = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	AspiraoCentral = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Redes = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	CFTV = 100000005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Acstica = 100000006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cabos = 100000007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ControledeAcesso = 100000008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	AcabamentosEltricos = 100000009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Eletrodomsticos = 100000010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Infraestrutura = 100000011,
}
#pragma warning restore CS1591
