#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tipodecomentario
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_1DefiniodeData = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	AlteraodeData = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Confirmao60dias = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Confirmao30dias = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Confirmao15dias = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	TentativadeContato = 100000005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ClienteSemResposta = 100000006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ObservaoGeral = 100000007,
}
#pragma warning restore CS1591
