#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_estadodoestoque
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Disponvel = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Reservado = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emshowroom = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Emconserto = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Perda = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Entregue = 100000005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NoReservado = 100000006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ParcialmenteReservado = 100000007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Separado = 100000008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Granular = 100000009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	FaturamentoDireto = 100000010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	EmprstimoDevolvido = 100000011,
}
#pragma warning restore CS1591
