#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_deposito
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	A = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	B = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	C = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	D = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	E = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	F = 100000005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	G = 100000006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	H = 100000007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	I = 100000008,
}
#pragma warning restore CS1591
