#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_tipodeconexao
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	HDMI = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	udioAnalgico = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Toslink = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Trigger12V = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Speaker = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ethernet = 100000005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	IR = 100000006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Serial = 100000007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	RF = 100000008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	RNET = 100000009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ACNET = 100000010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	PNET = 100000011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	LuzONOFF = 100000012,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	LuzTriacDimmer = 100000013,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	LuzPWMDimmer = 100000014,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Motor = 100000015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	GPIO = 100000016,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Power110V = 100000017,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Power220V = 100000018,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Aspirao = 100000019,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ControledeAcesso = 100000020,
}
#pragma warning restore CS1591
