#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum new_prazodeenviodemercadoria
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Imediato = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_7dias = 100000007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_15dias = 100000015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_30dias = 100000030,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_45dias = 100000045,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_60dias = 100000060,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_90dias = 100000090,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_120dias = 100000120,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	_180dias = 100000180,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Indefinido = 900000000,
}
#pragma warning restore CS1591
